// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openmanet/dashboard/v1/dashboard_service.proto

package dashboardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_openmanet_dashboard_v1_dashboard_service_proto protoreflect.FileDescriptor

const file_openmanet_dashboard_v1_dashboard_service_proto_rawDesc = "" +
	"\n" +
	".openmanet/dashboard/v1/dashboard_service.proto\x12\x16openmanet.dashboard.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a&openmanet/dashboard/v1/dashboard.proto2\xf1\x01\n" +
	"\x10DashboardService\x12`\n" +
	"\x12GetDashboardStatus\x12\x16.google.protobuf.Empty\x1a2.openmanet.dashboard.v1.GetDashboardStatusResponse\x12{\n" +
	"\x12ExecuteQuickAction\x121.openmanet.dashboard.v1.ExecuteQuickActionRequest\x1a2.openmanet.dashboard.v1.ExecuteQuickActionResponseB\xfe\x01\n" +
	"\x1acom.openmanet.dashboard.v1B\x15DashboardServiceProtoP\x01ZOgithub.com/openmanet/openmanetd/internal/api/openmanet/dashboard/v1;dashboardv1\xa2\x02\x03ODX\xaa\x02\x16Openmanet.Dashboard.V1\xca\x02\x16Openmanet\\Dashboard\\V1\xe2\x02\"Openmanet\\Dashboard\\V1\\GPBMetadata\xea\x02\x18Openmanet::Dashboard::V1b\x06proto3"

var file_openmanet_dashboard_v1_dashboard_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil),              // 0: google.protobuf.Empty
	(*ExecuteQuickActionRequest)(nil),  // 1: openmanet.dashboard.v1.ExecuteQuickActionRequest
	(*GetDashboardStatusResponse)(nil), // 2: openmanet.dashboard.v1.GetDashboardStatusResponse
	(*ExecuteQuickActionResponse)(nil), // 3: openmanet.dashboard.v1.ExecuteQuickActionResponse
}
var file_openmanet_dashboard_v1_dashboard_service_proto_depIdxs = []int32{
	0, // 0: openmanet.dashboard.v1.DashboardService.GetDashboardStatus:input_type -> google.protobuf.Empty
	1, // 1: openmanet.dashboard.v1.DashboardService.ExecuteQuickAction:input_type -> openmanet.dashboard.v1.ExecuteQuickActionRequest
	2, // 2: openmanet.dashboard.v1.DashboardService.GetDashboardStatus:output_type -> openmanet.dashboard.v1.GetDashboardStatusResponse
	3, // 3: openmanet.dashboard.v1.DashboardService.ExecuteQuickAction:output_type -> openmanet.dashboard.v1.ExecuteQuickActionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openmanet_dashboard_v1_dashboard_service_proto_init() }
func file_openmanet_dashboard_v1_dashboard_service_proto_init() {
	if File_openmanet_dashboard_v1_dashboard_service_proto != nil {
		return
	}
	file_openmanet_dashboard_v1_dashboard_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmanet_dashboard_v1_dashboard_service_proto_rawDesc), len(file_openmanet_dashboard_v1_dashboard_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openmanet_dashboard_v1_dashboard_service_proto_goTypes,
		DependencyIndexes: file_openmanet_dashboard_v1_dashboard_service_proto_depIdxs,
	}.Build()
	File_openmanet_dashboard_v1_dashboard_service_proto = out.File
	file_openmanet_dashboard_v1_dashboard_service_proto_goTypes = nil
	file_openmanet_dashboard_v1_dashboard_service_proto_depIdxs = nil
}
