env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
gomod:
  proxy: false
builds:
  - ldflags:
      - "-s -w"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - mips64
    mod_timestamp: "{{ .CommitTimestamp }}"
checksum:
  name_template: "{{ .Binary }}_checksums.txt"
archives:
  - name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    files:
      - README.md
