env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
gomod:
  proxy: false
builds:
  - ldflags:
      - "-s -w"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - mips64
    mod_timestamp: "{{ .CommitTimestamp }}"
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ end }}"
    files:
      - README.md
