// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.0
// source: openmanet/blos/v1/blos_service.proto

package blosv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BLOSServiceClient is the client API for BLOSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BLOSServiceClient interface {
	// GetBLOSStatus retrieves the current status of the BLOS subsystem, including whether it is enabled and any relevant status messages.
	GetBLOSStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetBLOSStatusResponse, error)
	// UpdateBLOSConfig updates the configuration of the BLOS subsystem, including enabling or disabling it and setting authentication keys.
	UpdateBLOSConfig(ctx context.Context, in *UpdateBLOSConfigRequest, opts ...grpc.CallOption) (*UpdateBLOSConfigResponse, error)
}

type bLOSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBLOSServiceClient(cc grpc.ClientConnInterface) BLOSServiceClient {
	return &bLOSServiceClient{cc}
}

func (c *bLOSServiceClient) GetBLOSStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetBLOSStatusResponse, error) {
	out := new(GetBLOSStatusResponse)
	err := c.cc.Invoke(ctx, "/openmanet.blos.v1.BLOSService/GetBLOSStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bLOSServiceClient) UpdateBLOSConfig(ctx context.Context, in *UpdateBLOSConfigRequest, opts ...grpc.CallOption) (*UpdateBLOSConfigResponse, error) {
	out := new(UpdateBLOSConfigResponse)
	err := c.cc.Invoke(ctx, "/openmanet.blos.v1.BLOSService/UpdateBLOSConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BLOSServiceServer is the server API for BLOSService service.
// All implementations must embed UnimplementedBLOSServiceServer
// for forward compatibility
type BLOSServiceServer interface {
	// GetBLOSStatus retrieves the current status of the BLOS subsystem, including whether it is enabled and any relevant status messages.
	GetBLOSStatus(context.Context, *emptypb.Empty) (*GetBLOSStatusResponse, error)
	// UpdateBLOSConfig updates the configuration of the BLOS subsystem, including enabling or disabling it and setting authentication keys.
	UpdateBLOSConfig(context.Context, *UpdateBLOSConfigRequest) (*UpdateBLOSConfigResponse, error)
	mustEmbedUnimplementedBLOSServiceServer()
}

// UnimplementedBLOSServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBLOSServiceServer struct {
}

func (UnimplementedBLOSServiceServer) GetBLOSStatus(context.Context, *emptypb.Empty) (*GetBLOSStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBLOSStatus not implemented")
}
func (UnimplementedBLOSServiceServer) UpdateBLOSConfig(context.Context, *UpdateBLOSConfigRequest) (*UpdateBLOSConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBLOSConfig not implemented")
}
func (UnimplementedBLOSServiceServer) mustEmbedUnimplementedBLOSServiceServer() {}

// UnsafeBLOSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BLOSServiceServer will
// result in compilation errors.
type UnsafeBLOSServiceServer interface {
	mustEmbedUnimplementedBLOSServiceServer()
}

func RegisterBLOSServiceServer(s grpc.ServiceRegistrar, srv BLOSServiceServer) {
	s.RegisterService(&BLOSService_ServiceDesc, srv)
}

func _BLOSService_GetBLOSStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BLOSServiceServer).GetBLOSStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.blos.v1.BLOSService/GetBLOSStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BLOSServiceServer).GetBLOSStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BLOSService_UpdateBLOSConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBLOSConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BLOSServiceServer).UpdateBLOSConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.blos.v1.BLOSService/UpdateBLOSConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BLOSServiceServer).UpdateBLOSConfig(ctx, req.(*UpdateBLOSConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BLOSService_ServiceDesc is the grpc.ServiceDesc for BLOSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BLOSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openmanet.blos.v1.BLOSService",
	HandlerType: (*BLOSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBLOSStatus",
			Handler:    _BLOSService_GetBLOSStatus_Handler,
		},
		{
			MethodName: "UpdateBLOSConfig",
			Handler:    _BLOSService_UpdateBLOSConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openmanet/blos/v1/blos_service.proto",
}
