// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openmanet/blos/v1/blos_service.proto

package blosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_openmanet_blos_v1_blos_service_proto protoreflect.FileDescriptor

const file_openmanet_blos_v1_blos_service_proto_rawDesc = "" +
	"\n" +
	"$openmanet/blos/v1/blos_service.proto\x12\x11openmanet.blos.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1copenmanet/blos/v1/blos.proto2\x83\x03\n" +
	"\vBLOSService\x12S\n" +
	"\rGetBLOSStatus\x12\x16.google.protobuf.Empty\x1a(.openmanet.blos.v1.GetBLOSStatusResponse\"\x00\x12m\n" +
	"\x10UpdateBLOSConfig\x12*.openmanet.blos.v1.UpdateBLOSConfigRequest\x1a+.openmanet.blos.v1.UpdateBLOSConfigResponse\"\x00\x12S\n" +
	"\rListBLOSPeers\x12\x16.google.protobuf.Empty\x1a(.openmanet.blos.v1.ListBLOSPeersResponse\"\x00\x12[\n" +
	"\x10StreamBLOSEvents\x12\x16.google.protobuf.Empty\x1a+.openmanet.blos.v1.StreamBLOSEventsResponse\"\x000\x01B\xd6\x01\n" +
	"\x15com.openmanet.blos.v1B\x10BlosServiceProtoP\x01ZEgithub.com/openmanet/openmanetd/internal/api/openmanet/blos/v1;blosv1\xa2\x02\x03OBX\xaa\x02\x11Openmanet.Blos.V1\xca\x02\x11Openmanet\\Blos\\V1\xe2\x02\x1dOpenmanet\\Blos\\V1\\GPBMetadata\xea\x02\x13Openmanet::Blos::V1b\x06proto3"

var file_openmanet_blos_v1_blos_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil),            // 0: google.protobuf.Empty
	(*UpdateBLOSConfigRequest)(nil),  // 1: openmanet.blos.v1.UpdateBLOSConfigRequest
	(*GetBLOSStatusResponse)(nil),    // 2: openmanet.blos.v1.GetBLOSStatusResponse
	(*UpdateBLOSConfigResponse)(nil), // 3: openmanet.blos.v1.UpdateBLOSConfigResponse
	(*ListBLOSPeersResponse)(nil),    // 4: openmanet.blos.v1.ListBLOSPeersResponse
	(*StreamBLOSEventsResponse)(nil), // 5: openmanet.blos.v1.StreamBLOSEventsResponse
}
var file_openmanet_blos_v1_blos_service_proto_depIdxs = []int32{
	0, // 0: openmanet.blos.v1.BLOSService.GetBLOSStatus:input_type -> google.protobuf.Empty
	1, // 1: openmanet.blos.v1.BLOSService.UpdateBLOSConfig:input_type -> openmanet.blos.v1.UpdateBLOSConfigRequest
	0, // 2: openmanet.blos.v1.BLOSService.ListBLOSPeers:input_type -> google.protobuf.Empty
	0, // 3: openmanet.blos.v1.BLOSService.StreamBLOSEvents:input_type -> google.protobuf.Empty
	2, // 4: openmanet.blos.v1.BLOSService.GetBLOSStatus:output_type -> openmanet.blos.v1.GetBLOSStatusResponse
	3, // 5: openmanet.blos.v1.BLOSService.UpdateBLOSConfig:output_type -> openmanet.blos.v1.UpdateBLOSConfigResponse
	4, // 6: openmanet.blos.v1.BLOSService.ListBLOSPeers:output_type -> openmanet.blos.v1.ListBLOSPeersResponse
	5, // 7: openmanet.blos.v1.BLOSService.StreamBLOSEvents:output_type -> openmanet.blos.v1.StreamBLOSEventsResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openmanet_blos_v1_blos_service_proto_init() }
func file_openmanet_blos_v1_blos_service_proto_init() {
	if File_openmanet_blos_v1_blos_service_proto != nil {
		return
	}
	file_openmanet_blos_v1_blos_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmanet_blos_v1_blos_service_proto_rawDesc), len(file_openmanet_blos_v1_blos_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openmanet_blos_v1_blos_service_proto_goTypes,
		DependencyIndexes: file_openmanet_blos_v1_blos_service_proto_depIdxs,
	}.Build()
	File_openmanet_blos_v1_blos_service_proto = out.File
	file_openmanet_blos_v1_blos_service_proto_goTypes = nil
	file_openmanet_blos_v1_blos_service_proto_depIdxs = nil
}
