// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: openmanet/gnss/v1/gnss_service.proto

package gnssv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/openmanet/openmanetd/internal/api/openmanet/gnss/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GNSSServiceName is the fully-qualified name of the GNSSService service.
	GNSSServiceName = "openmanet.gnss.v1.GNSSService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GNSSServiceGetGNSSStatusProcedure is the fully-qualified name of the GNSSService's GetGNSSStatus
	// RPC.
	GNSSServiceGetGNSSStatusProcedure = "/openmanet.gnss.v1.GNSSService/GetGNSSStatus"
	// GNSSServiceGetGNSSConfigProcedure is the fully-qualified name of the GNSSService's GetGNSSConfig
	// RPC.
	GNSSServiceGetGNSSConfigProcedure = "/openmanet.gnss.v1.GNSSService/GetGNSSConfig"
	// GNSSServiceUpdateGNSSConfigProcedure is the fully-qualified name of the GNSSService's
	// UpdateGNSSConfig RPC.
	GNSSServiceUpdateGNSSConfigProcedure = "/openmanet.gnss.v1.GNSSService/UpdateGNSSConfig"
)

// GNSSServiceClient is a client for the openmanet.gnss.v1.GNSSService service.
type GNSSServiceClient interface {
	// GetGNSSStatus returns the current GPS position fix and a snapshot of the
	// satellite constellation visible to the receiver. The response includes
	// individual satellite details (PRN, elevation, azimuth, SNR, and whether
	// the satellite is used in the navigation solution) as well as aggregate
	// dilution-of-precision metrics (PDOP, HDOP).
	//
	// Returns an empty response (not an error) when the GNSS subsystem is
	// disabled or the receiver hardware is not present.
	GetGNSSStatus(context.Context, *emptypb.Empty) (*v1.GetGNSSStatusResponse, error)
	// GetGNSSConfig returns the current GNSS receiver settings and output
	// protocol configuration as stored in the persistent config file. This
	// includes the enable/disable state, NMEA and CoT distribution toggles,
	// and the CoT UID.
	GetGNSSConfig(context.Context, *emptypb.Empty) (*v1.GetGNSSConfigResponse, error)
	// UpdateGNSSConfig persists the provided GNSS settings and output protocol
	// configuration to the config file and refreshes the in-memory state.
	// Changes take effect immediately for output protocol toggles; enabling or
	// disabling the GNSS receiver itself may require a service restart.
	//
	// Returns a CodeInternal error if the config file cannot be written.
	UpdateGNSSConfig(context.Context, *v1.UpdateGNSSConfigRequest) (*v1.UpdateGNSSConfigResponse, error)
}

// NewGNSSServiceClient constructs a client for the openmanet.gnss.v1.GNSSService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGNSSServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GNSSServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	gNSSServiceMethods := v1.File_openmanet_gnss_v1_gnss_service_proto.Services().ByName("GNSSService").Methods()
	return &gNSSServiceClient{
		getGNSSStatus: connect.NewClient[emptypb.Empty, v1.GetGNSSStatusResponse](
			httpClient,
			baseURL+GNSSServiceGetGNSSStatusProcedure,
			connect.WithSchema(gNSSServiceMethods.ByName("GetGNSSStatus")),
			connect.WithClientOptions(opts...),
		),
		getGNSSConfig: connect.NewClient[emptypb.Empty, v1.GetGNSSConfigResponse](
			httpClient,
			baseURL+GNSSServiceGetGNSSConfigProcedure,
			connect.WithSchema(gNSSServiceMethods.ByName("GetGNSSConfig")),
			connect.WithClientOptions(opts...),
		),
		updateGNSSConfig: connect.NewClient[v1.UpdateGNSSConfigRequest, v1.UpdateGNSSConfigResponse](
			httpClient,
			baseURL+GNSSServiceUpdateGNSSConfigProcedure,
			connect.WithSchema(gNSSServiceMethods.ByName("UpdateGNSSConfig")),
			connect.WithClientOptions(opts...),
		),
	}
}

// gNSSServiceClient implements GNSSServiceClient.
type gNSSServiceClient struct {
	getGNSSStatus    *connect.Client[emptypb.Empty, v1.GetGNSSStatusResponse]
	getGNSSConfig    *connect.Client[emptypb.Empty, v1.GetGNSSConfigResponse]
	updateGNSSConfig *connect.Client[v1.UpdateGNSSConfigRequest, v1.UpdateGNSSConfigResponse]
}

// GetGNSSStatus calls openmanet.gnss.v1.GNSSService.GetGNSSStatus.
func (c *gNSSServiceClient) GetGNSSStatus(ctx context.Context, req *emptypb.Empty) (*v1.GetGNSSStatusResponse, error) {
	response, err := c.getGNSSStatus.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetGNSSConfig calls openmanet.gnss.v1.GNSSService.GetGNSSConfig.
func (c *gNSSServiceClient) GetGNSSConfig(ctx context.Context, req *emptypb.Empty) (*v1.GetGNSSConfigResponse, error) {
	response, err := c.getGNSSConfig.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateGNSSConfig calls openmanet.gnss.v1.GNSSService.UpdateGNSSConfig.
func (c *gNSSServiceClient) UpdateGNSSConfig(ctx context.Context, req *v1.UpdateGNSSConfigRequest) (*v1.UpdateGNSSConfigResponse, error) {
	response, err := c.updateGNSSConfig.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GNSSServiceHandler is an implementation of the openmanet.gnss.v1.GNSSService service.
type GNSSServiceHandler interface {
	// GetGNSSStatus returns the current GPS position fix and a snapshot of the
	// satellite constellation visible to the receiver. The response includes
	// individual satellite details (PRN, elevation, azimuth, SNR, and whether
	// the satellite is used in the navigation solution) as well as aggregate
	// dilution-of-precision metrics (PDOP, HDOP).
	//
	// Returns an empty response (not an error) when the GNSS subsystem is
	// disabled or the receiver hardware is not present.
	GetGNSSStatus(context.Context, *emptypb.Empty) (*v1.GetGNSSStatusResponse, error)
	// GetGNSSConfig returns the current GNSS receiver settings and output
	// protocol configuration as stored in the persistent config file. This
	// includes the enable/disable state, NMEA and CoT distribution toggles,
	// and the CoT UID.
	GetGNSSConfig(context.Context, *emptypb.Empty) (*v1.GetGNSSConfigResponse, error)
	// UpdateGNSSConfig persists the provided GNSS settings and output protocol
	// configuration to the config file and refreshes the in-memory state.
	// Changes take effect immediately for output protocol toggles; enabling or
	// disabling the GNSS receiver itself may require a service restart.
	//
	// Returns a CodeInternal error if the config file cannot be written.
	UpdateGNSSConfig(context.Context, *v1.UpdateGNSSConfigRequest) (*v1.UpdateGNSSConfigResponse, error)
}

// NewGNSSServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGNSSServiceHandler(svc GNSSServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gNSSServiceMethods := v1.File_openmanet_gnss_v1_gnss_service_proto.Services().ByName("GNSSService").Methods()
	gNSSServiceGetGNSSStatusHandler := connect.NewUnaryHandlerSimple(
		GNSSServiceGetGNSSStatusProcedure,
		svc.GetGNSSStatus,
		connect.WithSchema(gNSSServiceMethods.ByName("GetGNSSStatus")),
		connect.WithHandlerOptions(opts...),
	)
	gNSSServiceGetGNSSConfigHandler := connect.NewUnaryHandlerSimple(
		GNSSServiceGetGNSSConfigProcedure,
		svc.GetGNSSConfig,
		connect.WithSchema(gNSSServiceMethods.ByName("GetGNSSConfig")),
		connect.WithHandlerOptions(opts...),
	)
	gNSSServiceUpdateGNSSConfigHandler := connect.NewUnaryHandlerSimple(
		GNSSServiceUpdateGNSSConfigProcedure,
		svc.UpdateGNSSConfig,
		connect.WithSchema(gNSSServiceMethods.ByName("UpdateGNSSConfig")),
		connect.WithHandlerOptions(opts...),
	)
	return "/openmanet.gnss.v1.GNSSService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GNSSServiceGetGNSSStatusProcedure:
			gNSSServiceGetGNSSStatusHandler.ServeHTTP(w, r)
		case GNSSServiceGetGNSSConfigProcedure:
			gNSSServiceGetGNSSConfigHandler.ServeHTTP(w, r)
		case GNSSServiceUpdateGNSSConfigProcedure:
			gNSSServiceUpdateGNSSConfigHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGNSSServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGNSSServiceHandler struct{}

func (UnimplementedGNSSServiceHandler) GetGNSSStatus(context.Context, *emptypb.Empty) (*v1.GetGNSSStatusResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.gnss.v1.GNSSService.GetGNSSStatus is not implemented"))
}

func (UnimplementedGNSSServiceHandler) GetGNSSConfig(context.Context, *emptypb.Empty) (*v1.GetGNSSConfigResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.gnss.v1.GNSSService.GetGNSSConfig is not implemented"))
}

func (UnimplementedGNSSServiceHandler) UpdateGNSSConfig(context.Context, *v1.UpdateGNSSConfigRequest) (*v1.UpdateGNSSConfigResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.gnss.v1.GNSSService.UpdateGNSSConfig is not implemented"))
}
