// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"
)

type Node struct {
	MacAddr      string
	Hostname     string
	IpAddr       string
	UciDhcpStart sql.NullInt64
	UciDhcpLimit sql.NullInt64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
