// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openmanet/network/v1/mesh_neighbors.proto

package networkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MeshNeighbors is the Alfred payload published by every OpenMANET node
// under DATA_TYPE_MESH_NEIGHBORS (103). Carries each node's view of its
// direct L2 batman-adv neighbors, partitioned by the interface (RF vs
// vxlan0 tunnel) on which each neighbor is heard, plus the publisher's
// own best-route tree. Consumed by the mesh topology handler for
// mesh-wide edge/segment classification and multi-hop chain resolution.
type MeshNeighbors struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Primary MAC of the publishing node. Redundant with Alfred's
	// per-record Source envelope but convenient for downstream code that
	// does not plumb the envelope through.
	PrimaryMac string `protobuf:"bytes,1,opt,name=primary_mac,json=primaryMac,proto3" json:"primary_mac,omitempty"`
	// Base hostname ("_<iface>" suffix stripped). Lets consumers
	// correlate to bat-hosts and vis by hostname when MACs disagree.
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Batman-adv algorithm ID as reported by `batctl mj`. 4 = BATMAN_IV,
	// 15 = BATMAN_V. Drives metric interpretation.
	Algorithm int32 `protobuf:"varint,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// Every direct batman-adv neighbor visible to the publishing node.
	Neighbors []*MeshNeighbor `protobuf:"bytes,4,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	// Publisher's wall clock at refresh time. Consumers treat records
	// older than 3x the publish interval as stale.
	CollectedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	// Publisher's own best-route tree (`batctl oj`, Best==true rows only).
	// Enables remote-perspective my-paths rendering and multi-hop vxlan0
	// chain resolution on the consumer side. Empty when the publisher is
	// running in a reduced-bandwidth mode.
	Originators   []*Originator `protobuf:"bytes,6,rep,name=originators,proto3" json:"originators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshNeighbors) Reset() {
	*x = MeshNeighbors{}
	mi := &file_openmanet_network_v1_mesh_neighbors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshNeighbors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshNeighbors) ProtoMessage() {}

func (x *MeshNeighbors) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_network_v1_mesh_neighbors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshNeighbors.ProtoReflect.Descriptor instead.
func (*MeshNeighbors) Descriptor() ([]byte, []int) {
	return file_openmanet_network_v1_mesh_neighbors_proto_rawDescGZIP(), []int{0}
}

func (x *MeshNeighbors) GetPrimaryMac() string {
	if x != nil {
		return x.PrimaryMac
	}
	return ""
}

func (x *MeshNeighbors) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MeshNeighbors) GetAlgorithm() int32 {
	if x != nil {
		return x.Algorithm
	}
	return 0
}

func (x *MeshNeighbors) GetNeighbors() []*MeshNeighbor {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

func (x *MeshNeighbors) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *MeshNeighbors) GetOriginators() []*Originator {
	if x != nil {
		return x.Originators
	}
	return nil
}

// MeshNeighbor records one direct batman-adv neighbor from the
// publishing node's perspective.
type MeshNeighbor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Neighbor's MAC (lowercased).
	Mac string `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	// Hard interface name the neighbor is reached on ("wlan0", "vxlan0",
	// "eth0", etc.) as reported by `batctl nj`.
	HardIfname string `protobuf:"bytes,2,opt,name=hard_ifname,json=hardIfname,proto3" json:"hard_ifname,omitempty"`
	// Convenience: hard_ifname == "vxlan0". Pre-computed so downstream
	// consumers do not re-implement the check.
	Blos bool `protobuf:"varint,3,opt,name=blos,proto3" json:"blos,omitempty"`
	// Last-seen age in milliseconds (from `batctl nj`). 0 if unknown.
	LastSeenMsecs int32 `protobuf:"varint,4,opt,name=last_seen_msecs,json=lastSeenMsecs,proto3" json:"last_seen_msecs,omitempty"`
	// BATMAN_V link throughput in kbps. 0 on BATMAN_IV or if unknown.
	ThroughputKbps int64 `protobuf:"varint,5,opt,name=throughput_kbps,json=throughputKbps,proto3" json:"throughput_kbps,omitempty"`
	// BATMAN_IV transmit quality (0-255). 0 on BATMAN_V or if unknown.
	Tq            int32 `protobuf:"varint,6,opt,name=tq,proto3" json:"tq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshNeighbor) Reset() {
	*x = MeshNeighbor{}
	mi := &file_openmanet_network_v1_mesh_neighbors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshNeighbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshNeighbor) ProtoMessage() {}

func (x *MeshNeighbor) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_network_v1_mesh_neighbors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshNeighbor.ProtoReflect.Descriptor instead.
func (*MeshNeighbor) Descriptor() ([]byte, []int) {
	return file_openmanet_network_v1_mesh_neighbors_proto_rawDescGZIP(), []int{1}
}

func (x *MeshNeighbor) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *MeshNeighbor) GetHardIfname() string {
	if x != nil {
		return x.HardIfname
	}
	return ""
}

func (x *MeshNeighbor) GetBlos() bool {
	if x != nil {
		return x.Blos
	}
	return false
}

func (x *MeshNeighbor) GetLastSeenMsecs() int32 {
	if x != nil {
		return x.LastSeenMsecs
	}
	return 0
}

func (x *MeshNeighbor) GetThroughputKbps() int64 {
	if x != nil {
		return x.ThroughputKbps
	}
	return 0
}

func (x *MeshNeighbor) GetTq() int32 {
	if x != nil {
		return x.Tq
	}
	return 0
}

// Originator is one row of the publisher's best-route table (equivalent
// to a single `Best==true` entry from `batctl oj`). The consumer uses
// the mesh-wide collection of these rows to render remote nodes'
// perspective overlays and to resolve multi-hop tunnel chains.
type Originator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination MAC (lowercased).
	OrigMac string `protobuf:"bytes,1,opt,name=orig_mac,json=origMac,proto3" json:"orig_mac,omitempty"`
	// Next hop the publisher would use to reach orig_mac (lowercased).
	// Equal to orig_mac when orig_mac is a direct neighbor.
	NextHopMac string `protobuf:"bytes,2,opt,name=next_hop_mac,json=nextHopMac,proto3" json:"next_hop_mac,omitempty"`
	// Publisher's hops to orig_mac. 1 for direct neighbors.
	Hops int32 `protobuf:"varint,3,opt,name=hops,proto3" json:"hops,omitempty"`
	// Publisher's hard_ifname used for this route ("wlan0", "vxlan0", ...).
	HardIfname string `protobuf:"bytes,4,opt,name=hard_ifname,json=hardIfname,proto3" json:"hard_ifname,omitempty"`
	// BATMAN_V link throughput in kbps along this route. 0 on IV.
	ThroughputKbps int64 `protobuf:"varint,5,opt,name=throughput_kbps,json=throughputKbps,proto3" json:"throughput_kbps,omitempty"`
	// BATMAN_IV transmit quality (0-255). 0 on V.
	Tq            int32 `protobuf:"varint,6,opt,name=tq,proto3" json:"tq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Originator) Reset() {
	*x = Originator{}
	mi := &file_openmanet_network_v1_mesh_neighbors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Originator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Originator) ProtoMessage() {}

func (x *Originator) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_network_v1_mesh_neighbors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Originator.ProtoReflect.Descriptor instead.
func (*Originator) Descriptor() ([]byte, []int) {
	return file_openmanet_network_v1_mesh_neighbors_proto_rawDescGZIP(), []int{2}
}

func (x *Originator) GetOrigMac() string {
	if x != nil {
		return x.OrigMac
	}
	return ""
}

func (x *Originator) GetNextHopMac() string {
	if x != nil {
		return x.NextHopMac
	}
	return ""
}

func (x *Originator) GetHops() int32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

func (x *Originator) GetHardIfname() string {
	if x != nil {
		return x.HardIfname
	}
	return ""
}

func (x *Originator) GetThroughputKbps() int64 {
	if x != nil {
		return x.ThroughputKbps
	}
	return 0
}

func (x *Originator) GetTq() int32 {
	if x != nil {
		return x.Tq
	}
	return 0
}

var File_openmanet_network_v1_mesh_neighbors_proto protoreflect.FileDescriptor

const file_openmanet_network_v1_mesh_neighbors_proto_rawDesc = "" +
	"\n" +
	")openmanet/network/v1/mesh_neighbors.proto\x12\x14openmanet.network.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x02\n" +
	"\rMeshNeighbors\x12\x1f\n" +
	"\vprimary_mac\x18\x01 \x01(\tR\n" +
	"primaryMac\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\x05R\talgorithm\x12@\n" +
	"\tneighbors\x18\x04 \x03(\v2\".openmanet.network.v1.MeshNeighborR\tneighbors\x12=\n" +
	"\fcollected_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x12B\n" +
	"\voriginators\x18\x06 \x03(\v2 .openmanet.network.v1.OriginatorR\voriginators\"\xb6\x01\n" +
	"\fMeshNeighbor\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\tR\x03mac\x12\x1f\n" +
	"\vhard_ifname\x18\x02 \x01(\tR\n" +
	"hardIfname\x12\x12\n" +
	"\x04blos\x18\x03 \x01(\bR\x04blos\x12&\n" +
	"\x0flast_seen_msecs\x18\x04 \x01(\x05R\rlastSeenMsecs\x12'\n" +
	"\x0fthroughput_kbps\x18\x05 \x01(\x03R\x0ethroughputKbps\x12\x0e\n" +
	"\x02tq\x18\x06 \x01(\x05R\x02tq\"\xb7\x01\n" +
	"\n" +
	"Originator\x12\x19\n" +
	"\borig_mac\x18\x01 \x01(\tR\aorigMac\x12 \n" +
	"\fnext_hop_mac\x18\x02 \x01(\tR\n" +
	"nextHopMac\x12\x12\n" +
	"\x04hops\x18\x03 \x01(\x05R\x04hops\x12\x1f\n" +
	"\vhard_ifname\x18\x04 \x01(\tR\n" +
	"hardIfname\x12'\n" +
	"\x0fthroughput_kbps\x18\x05 \x01(\x03R\x0ethroughputKbps\x12\x0e\n" +
	"\x02tq\x18\x06 \x01(\x05R\x02tqB\xed\x01\n" +
	"\x18com.openmanet.network.v1B\x12MeshNeighborsProtoP\x01ZKgithub.com/openmanet/openmanetd/internal/api/openmanet/network/v1;networkv1\xa2\x02\x03ONX\xaa\x02\x14Openmanet.Network.V1\xca\x02\x14Openmanet\\Network\\V1\xe2\x02 Openmanet\\Network\\V1\\GPBMetadata\xea\x02\x16Openmanet::Network::V1b\x06proto3"

var (
	file_openmanet_network_v1_mesh_neighbors_proto_rawDescOnce sync.Once
	file_openmanet_network_v1_mesh_neighbors_proto_rawDescData []byte
)

func file_openmanet_network_v1_mesh_neighbors_proto_rawDescGZIP() []byte {
	file_openmanet_network_v1_mesh_neighbors_proto_rawDescOnce.Do(func() {
		file_openmanet_network_v1_mesh_neighbors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openmanet_network_v1_mesh_neighbors_proto_rawDesc), len(file_openmanet_network_v1_mesh_neighbors_proto_rawDesc)))
	})
	return file_openmanet_network_v1_mesh_neighbors_proto_rawDescData
}

var file_openmanet_network_v1_mesh_neighbors_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_openmanet_network_v1_mesh_neighbors_proto_goTypes = []any{
	(*MeshNeighbors)(nil),         // 0: openmanet.network.v1.MeshNeighbors
	(*MeshNeighbor)(nil),          // 1: openmanet.network.v1.MeshNeighbor
	(*Originator)(nil),            // 2: openmanet.network.v1.Originator
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_openmanet_network_v1_mesh_neighbors_proto_depIdxs = []int32{
	1, // 0: openmanet.network.v1.MeshNeighbors.neighbors:type_name -> openmanet.network.v1.MeshNeighbor
	3, // 1: openmanet.network.v1.MeshNeighbors.collected_at:type_name -> google.protobuf.Timestamp
	2, // 2: openmanet.network.v1.MeshNeighbors.originators:type_name -> openmanet.network.v1.Originator
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_openmanet_network_v1_mesh_neighbors_proto_init() }
func file_openmanet_network_v1_mesh_neighbors_proto_init() {
	if File_openmanet_network_v1_mesh_neighbors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmanet_network_v1_mesh_neighbors_proto_rawDesc), len(file_openmanet_network_v1_mesh_neighbors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openmanet_network_v1_mesh_neighbors_proto_goTypes,
		DependencyIndexes: file_openmanet_network_v1_mesh_neighbors_proto_depIdxs,
		MessageInfos:      file_openmanet_network_v1_mesh_neighbors_proto_msgTypes,
	}.Build()
	File_openmanet_network_v1_mesh_neighbors_proto = out.File
	file_openmanet_network_v1_mesh_neighbors_proto_goTypes = nil
	file_openmanet_network_v1_mesh_neighbors_proto_depIdxs = nil
}
