// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openmanet/network_interface/v1/dhcp.proto

package network_interfacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DHCPServerConfig describes the DHCP server settings for a network interface.
type DHCPServerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The UCI interface name the DHCP pool is bound to (e.g. "BR-AHWLAN").
	InterfaceName string `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// The first assignable IP address in the DHCP range.
	RangeStart string `protobuf:"bytes,2,opt,name=range_start,json=rangeStart,proto3" json:"range_start,omitempty"`
	// The last assignable IP address in the DHCP range.
	RangeEnd string `protobuf:"bytes,3,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	// The lease duration as a human-readable string (e.g. "12h").
	LeaseTime string `protobuf:"bytes,4,opt,name=lease_time,json=leaseTime,proto3" json:"lease_time,omitempty"`
	// Whether DNS forwarding is enabled for this DHCP pool.
	DnsForwardingEnabled bool `protobuf:"varint,5,opt,name=dns_forwarding_enabled,json=dnsForwardingEnabled,proto3" json:"dns_forwarding_enabled,omitempty"`
	// The number of currently active DHCP leases.
	ActiveLeaseCount int32 `protobuf:"varint,6,opt,name=active_lease_count,json=activeLeaseCount,proto3" json:"active_lease_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DHCPServerConfig) Reset() {
	*x = DHCPServerConfig{}
	mi := &file_openmanet_network_interface_v1_dhcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DHCPServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DHCPServerConfig) ProtoMessage() {}

func (x *DHCPServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_network_interface_v1_dhcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DHCPServerConfig.ProtoReflect.Descriptor instead.
func (*DHCPServerConfig) Descriptor() ([]byte, []int) {
	return file_openmanet_network_interface_v1_dhcp_proto_rawDescGZIP(), []int{0}
}

func (x *DHCPServerConfig) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *DHCPServerConfig) GetRangeStart() string {
	if x != nil {
		return x.RangeStart
	}
	return ""
}

func (x *DHCPServerConfig) GetRangeEnd() string {
	if x != nil {
		return x.RangeEnd
	}
	return ""
}

func (x *DHCPServerConfig) GetLeaseTime() string {
	if x != nil {
		return x.LeaseTime
	}
	return ""
}

func (x *DHCPServerConfig) GetDnsForwardingEnabled() bool {
	if x != nil {
		return x.DnsForwardingEnabled
	}
	return false
}

func (x *DHCPServerConfig) GetActiveLeaseCount() int32 {
	if x != nil {
		return x.ActiveLeaseCount
	}
	return 0
}

// Response message for retrieving DHCP server configuration.
type GetDHCPServerConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The DHCP server configuration.
	Config        *DHCPServerConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDHCPServerConfigResponse) Reset() {
	*x = GetDHCPServerConfigResponse{}
	mi := &file_openmanet_network_interface_v1_dhcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDHCPServerConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDHCPServerConfigResponse) ProtoMessage() {}

func (x *GetDHCPServerConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_network_interface_v1_dhcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDHCPServerConfigResponse.ProtoReflect.Descriptor instead.
func (*GetDHCPServerConfigResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_network_interface_v1_dhcp_proto_rawDescGZIP(), []int{1}
}

func (x *GetDHCPServerConfigResponse) GetConfig() *DHCPServerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// ActiveDHCPLease represents a currently active DHCP lease.
type ActiveDHCPLease struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The hostname of the leased device, if available.
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// The MAC address of the leased device.
	MacAddress string `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	// The leased IPv4 address.
	IpAddress string `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Seconds remaining until the lease expires.
	ExpiresSeconds int32 `protobuf:"varint,4,opt,name=expires_seconds,json=expiresSeconds,proto3" json:"expires_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActiveDHCPLease) Reset() {
	*x = ActiveDHCPLease{}
	mi := &file_openmanet_network_interface_v1_dhcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveDHCPLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveDHCPLease) ProtoMessage() {}

func (x *ActiveDHCPLease) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_network_interface_v1_dhcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveDHCPLease.ProtoReflect.Descriptor instead.
func (*ActiveDHCPLease) Descriptor() ([]byte, []int) {
	return file_openmanet_network_interface_v1_dhcp_proto_rawDescGZIP(), []int{2}
}

func (x *ActiveDHCPLease) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ActiveDHCPLease) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *ActiveDHCPLease) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ActiveDHCPLease) GetExpiresSeconds() int32 {
	if x != nil {
		return x.ExpiresSeconds
	}
	return 0
}

// Response message for listing active DHCP leases.
type ListActiveDHCPLeasesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All currently active DHCP leases.
	Leases        []*ActiveDHCPLease `protobuf:"bytes,1,rep,name=leases,proto3" json:"leases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveDHCPLeasesResponse) Reset() {
	*x = ListActiveDHCPLeasesResponse{}
	mi := &file_openmanet_network_interface_v1_dhcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveDHCPLeasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveDHCPLeasesResponse) ProtoMessage() {}

func (x *ListActiveDHCPLeasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_network_interface_v1_dhcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveDHCPLeasesResponse.ProtoReflect.Descriptor instead.
func (*ListActiveDHCPLeasesResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_network_interface_v1_dhcp_proto_rawDescGZIP(), []int{3}
}

func (x *ListActiveDHCPLeasesResponse) GetLeases() []*ActiveDHCPLease {
	if x != nil {
		return x.Leases
	}
	return nil
}

// StaticDHCPLease represents a manually configured static DHCP reservation.
type StaticDHCPLease struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The hostname for the static reservation.
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// The MAC address for the static reservation.
	MacAddress string `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	// The reserved IPv4 address.
	IpAddress     string `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticDHCPLease) Reset() {
	*x = StaticDHCPLease{}
	mi := &file_openmanet_network_interface_v1_dhcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticDHCPLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticDHCPLease) ProtoMessage() {}

func (x *StaticDHCPLease) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_network_interface_v1_dhcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticDHCPLease.ProtoReflect.Descriptor instead.
func (*StaticDHCPLease) Descriptor() ([]byte, []int) {
	return file_openmanet_network_interface_v1_dhcp_proto_rawDescGZIP(), []int{4}
}

func (x *StaticDHCPLease) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *StaticDHCPLease) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *StaticDHCPLease) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

// Response message for listing static DHCP leases.
type ListStaticDHCPLeasesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All configured static DHCP reservations.
	Leases        []*StaticDHCPLease `protobuf:"bytes,1,rep,name=leases,proto3" json:"leases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStaticDHCPLeasesResponse) Reset() {
	*x = ListStaticDHCPLeasesResponse{}
	mi := &file_openmanet_network_interface_v1_dhcp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStaticDHCPLeasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStaticDHCPLeasesResponse) ProtoMessage() {}

func (x *ListStaticDHCPLeasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_network_interface_v1_dhcp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStaticDHCPLeasesResponse.ProtoReflect.Descriptor instead.
func (*ListStaticDHCPLeasesResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_network_interface_v1_dhcp_proto_rawDescGZIP(), []int{5}
}

func (x *ListStaticDHCPLeasesResponse) GetLeases() []*StaticDHCPLease {
	if x != nil {
		return x.Leases
	}
	return nil
}

var File_openmanet_network_interface_v1_dhcp_proto protoreflect.FileDescriptor

const file_openmanet_network_interface_v1_dhcp_proto_rawDesc = "" +
	"\n" +
	")openmanet/network_interface/v1/dhcp.proto\x12\x1eopenmanet.network_interface.v1\"\xfa\x01\n" +
	"\x10DHCPServerConfig\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x1f\n" +
	"\vrange_start\x18\x02 \x01(\tR\n" +
	"rangeStart\x12\x1b\n" +
	"\trange_end\x18\x03 \x01(\tR\brangeEnd\x12\x1d\n" +
	"\n" +
	"lease_time\x18\x04 \x01(\tR\tleaseTime\x124\n" +
	"\x16dns_forwarding_enabled\x18\x05 \x01(\bR\x14dnsForwardingEnabled\x12,\n" +
	"\x12active_lease_count\x18\x06 \x01(\x05R\x10activeLeaseCount\"g\n" +
	"\x1bGetDHCPServerConfigResponse\x12H\n" +
	"\x06config\x18\x01 \x01(\v20.openmanet.network_interface.v1.DHCPServerConfigR\x06config\"\x96\x01\n" +
	"\x0fActiveDHCPLease\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12'\n" +
	"\x0fexpires_seconds\x18\x04 \x01(\x05R\x0eexpiresSeconds\"g\n" +
	"\x1cListActiveDHCPLeasesResponse\x12G\n" +
	"\x06leases\x18\x01 \x03(\v2/.openmanet.network_interface.v1.ActiveDHCPLeaseR\x06leases\"m\n" +
	"\x0fStaticDHCPLease\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\"g\n" +
	"\x1cListStaticDHCPLeasesResponse\x12G\n" +
	"\x06leases\x18\x01 \x03(\v2/.openmanet.network_interface.v1.StaticDHCPLeaseR\x06leasesB\xa6\x02\n" +
	"\"com.openmanet.network_interface.v1B\tDhcpProtoP\x01Z_github.com/openmanet/openmanetd/internal/api/openmanet/network_interface/v1;network_interfacev1\xa2\x02\x03ONX\xaa\x02\x1dOpenmanet.NetworkInterface.V1\xca\x02\x1dOpenmanet\\NetworkInterface\\V1\xe2\x02)Openmanet\\NetworkInterface\\V1\\GPBMetadata\xea\x02\x1fOpenmanet::NetworkInterface::V1b\x06proto3"

var (
	file_openmanet_network_interface_v1_dhcp_proto_rawDescOnce sync.Once
	file_openmanet_network_interface_v1_dhcp_proto_rawDescData []byte
)

func file_openmanet_network_interface_v1_dhcp_proto_rawDescGZIP() []byte {
	file_openmanet_network_interface_v1_dhcp_proto_rawDescOnce.Do(func() {
		file_openmanet_network_interface_v1_dhcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openmanet_network_interface_v1_dhcp_proto_rawDesc), len(file_openmanet_network_interface_v1_dhcp_proto_rawDesc)))
	})
	return file_openmanet_network_interface_v1_dhcp_proto_rawDescData
}

var file_openmanet_network_interface_v1_dhcp_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_openmanet_network_interface_v1_dhcp_proto_goTypes = []any{
	(*DHCPServerConfig)(nil),             // 0: openmanet.network_interface.v1.DHCPServerConfig
	(*GetDHCPServerConfigResponse)(nil),  // 1: openmanet.network_interface.v1.GetDHCPServerConfigResponse
	(*ActiveDHCPLease)(nil),              // 2: openmanet.network_interface.v1.ActiveDHCPLease
	(*ListActiveDHCPLeasesResponse)(nil), // 3: openmanet.network_interface.v1.ListActiveDHCPLeasesResponse
	(*StaticDHCPLease)(nil),              // 4: openmanet.network_interface.v1.StaticDHCPLease
	(*ListStaticDHCPLeasesResponse)(nil), // 5: openmanet.network_interface.v1.ListStaticDHCPLeasesResponse
}
var file_openmanet_network_interface_v1_dhcp_proto_depIdxs = []int32{
	0, // 0: openmanet.network_interface.v1.GetDHCPServerConfigResponse.config:type_name -> openmanet.network_interface.v1.DHCPServerConfig
	2, // 1: openmanet.network_interface.v1.ListActiveDHCPLeasesResponse.leases:type_name -> openmanet.network_interface.v1.ActiveDHCPLease
	4, // 2: openmanet.network_interface.v1.ListStaticDHCPLeasesResponse.leases:type_name -> openmanet.network_interface.v1.StaticDHCPLease
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_openmanet_network_interface_v1_dhcp_proto_init() }
func file_openmanet_network_interface_v1_dhcp_proto_init() {
	if File_openmanet_network_interface_v1_dhcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmanet_network_interface_v1_dhcp_proto_rawDesc), len(file_openmanet_network_interface_v1_dhcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openmanet_network_interface_v1_dhcp_proto_goTypes,
		DependencyIndexes: file_openmanet_network_interface_v1_dhcp_proto_depIdxs,
		MessageInfos:      file_openmanet_network_interface_v1_dhcp_proto_msgTypes,
	}.Build()
	File_openmanet_network_interface_v1_dhcp_proto = out.File
	file_openmanet_network_interface_v1_dhcp_proto_goTypes = nil
	file_openmanet_network_interface_v1_dhcp_proto_depIdxs = nil
}
