// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.0
// source: openmanet/network_interface/v1/network_interface_service.proto

package network_interfacev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NetworkInterfaceServiceClient is the client API for NetworkInterfaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkInterfaceServiceClient interface {
	// ListNetworkInterfaces returns all network interfaces with their current
	// status, addresses, traffic counters, and MTU.
	ListNetworkInterfaces(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListNetworkInterfacesResponse, error)
	// GetDHCPServerConfig returns the active DHCP server configuration,
	// including the address range, lease time, and DNS forwarding status.
	GetDHCPServerConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetDHCPServerConfigResponse, error)
	// ListActiveDHCPLeases returns all currently active DHCP leases issued
	// by the dnsmasq DHCP server.
	ListActiveDHCPLeases(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListActiveDHCPLeasesResponse, error)
	// ListStaticDHCPLeases returns all manually configured static DHCP
	// reservations (host sections in UCI dhcp config).
	ListStaticDHCPLeases(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListStaticDHCPLeasesResponse, error)
}

type networkInterfaceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkInterfaceServiceClient(cc grpc.ClientConnInterface) NetworkInterfaceServiceClient {
	return &networkInterfaceServiceClient{cc}
}

func (c *networkInterfaceServiceClient) ListNetworkInterfaces(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListNetworkInterfacesResponse, error) {
	out := new(ListNetworkInterfacesResponse)
	err := c.cc.Invoke(ctx, "/openmanet.network_interface.v1.NetworkInterfaceService/ListNetworkInterfaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkInterfaceServiceClient) GetDHCPServerConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetDHCPServerConfigResponse, error) {
	out := new(GetDHCPServerConfigResponse)
	err := c.cc.Invoke(ctx, "/openmanet.network_interface.v1.NetworkInterfaceService/GetDHCPServerConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkInterfaceServiceClient) ListActiveDHCPLeases(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListActiveDHCPLeasesResponse, error) {
	out := new(ListActiveDHCPLeasesResponse)
	err := c.cc.Invoke(ctx, "/openmanet.network_interface.v1.NetworkInterfaceService/ListActiveDHCPLeases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkInterfaceServiceClient) ListStaticDHCPLeases(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListStaticDHCPLeasesResponse, error) {
	out := new(ListStaticDHCPLeasesResponse)
	err := c.cc.Invoke(ctx, "/openmanet.network_interface.v1.NetworkInterfaceService/ListStaticDHCPLeases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkInterfaceServiceServer is the server API for NetworkInterfaceService service.
// All implementations must embed UnimplementedNetworkInterfaceServiceServer
// for forward compatibility
type NetworkInterfaceServiceServer interface {
	// ListNetworkInterfaces returns all network interfaces with their current
	// status, addresses, traffic counters, and MTU.
	ListNetworkInterfaces(context.Context, *emptypb.Empty) (*ListNetworkInterfacesResponse, error)
	// GetDHCPServerConfig returns the active DHCP server configuration,
	// including the address range, lease time, and DNS forwarding status.
	GetDHCPServerConfig(context.Context, *emptypb.Empty) (*GetDHCPServerConfigResponse, error)
	// ListActiveDHCPLeases returns all currently active DHCP leases issued
	// by the dnsmasq DHCP server.
	ListActiveDHCPLeases(context.Context, *emptypb.Empty) (*ListActiveDHCPLeasesResponse, error)
	// ListStaticDHCPLeases returns all manually configured static DHCP
	// reservations (host sections in UCI dhcp config).
	ListStaticDHCPLeases(context.Context, *emptypb.Empty) (*ListStaticDHCPLeasesResponse, error)
	mustEmbedUnimplementedNetworkInterfaceServiceServer()
}

// UnimplementedNetworkInterfaceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNetworkInterfaceServiceServer struct {
}

func (UnimplementedNetworkInterfaceServiceServer) ListNetworkInterfaces(context.Context, *emptypb.Empty) (*ListNetworkInterfacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNetworkInterfaces not implemented")
}
func (UnimplementedNetworkInterfaceServiceServer) GetDHCPServerConfig(context.Context, *emptypb.Empty) (*GetDHCPServerConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDHCPServerConfig not implemented")
}
func (UnimplementedNetworkInterfaceServiceServer) ListActiveDHCPLeases(context.Context, *emptypb.Empty) (*ListActiveDHCPLeasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActiveDHCPLeases not implemented")
}
func (UnimplementedNetworkInterfaceServiceServer) ListStaticDHCPLeases(context.Context, *emptypb.Empty) (*ListStaticDHCPLeasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStaticDHCPLeases not implemented")
}
func (UnimplementedNetworkInterfaceServiceServer) mustEmbedUnimplementedNetworkInterfaceServiceServer() {
}

// UnsafeNetworkInterfaceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkInterfaceServiceServer will
// result in compilation errors.
type UnsafeNetworkInterfaceServiceServer interface {
	mustEmbedUnimplementedNetworkInterfaceServiceServer()
}

func RegisterNetworkInterfaceServiceServer(s grpc.ServiceRegistrar, srv NetworkInterfaceServiceServer) {
	s.RegisterService(&NetworkInterfaceService_ServiceDesc, srv)
}

func _NetworkInterfaceService_ListNetworkInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkInterfaceServiceServer).ListNetworkInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.network_interface.v1.NetworkInterfaceService/ListNetworkInterfaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkInterfaceServiceServer).ListNetworkInterfaces(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkInterfaceService_GetDHCPServerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkInterfaceServiceServer).GetDHCPServerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.network_interface.v1.NetworkInterfaceService/GetDHCPServerConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkInterfaceServiceServer).GetDHCPServerConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkInterfaceService_ListActiveDHCPLeases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkInterfaceServiceServer).ListActiveDHCPLeases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.network_interface.v1.NetworkInterfaceService/ListActiveDHCPLeases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkInterfaceServiceServer).ListActiveDHCPLeases(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkInterfaceService_ListStaticDHCPLeases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkInterfaceServiceServer).ListStaticDHCPLeases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.network_interface.v1.NetworkInterfaceService/ListStaticDHCPLeases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkInterfaceServiceServer).ListStaticDHCPLeases(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkInterfaceService_ServiceDesc is the grpc.ServiceDesc for NetworkInterfaceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkInterfaceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openmanet.network_interface.v1.NetworkInterfaceService",
	HandlerType: (*NetworkInterfaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNetworkInterfaces",
			Handler:    _NetworkInterfaceService_ListNetworkInterfaces_Handler,
		},
		{
			MethodName: "GetDHCPServerConfig",
			Handler:    _NetworkInterfaceService_GetDHCPServerConfig_Handler,
		},
		{
			MethodName: "ListActiveDHCPLeases",
			Handler:    _NetworkInterfaceService_ListActiveDHCPLeases_Handler,
		},
		{
			MethodName: "ListStaticDHCPLeases",
			Handler:    _NetworkInterfaceService_ListStaticDHCPLeases_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openmanet/network_interface/v1/network_interface_service.proto",
}
