// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openmanet/service/v1/station.proto

package servicev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StationInfo represents statistics and information for a connected station.
type StationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The interface index that this station is associated with.
	InterfaceIndex int32 `protobuf:"varint,1,opt,name=interface_index,json=interfaceIndex,proto3" json:"interface_index,omitempty"`
	// The hardware address (MAC) of the station.
	HardwareAddress string `protobuf:"bytes,2,opt,name=hardware_address,json=hardwareAddress,proto3" json:"hardware_address,omitempty"`
	// The time since the station last connected.
	Connected *durationpb.Duration `protobuf:"bytes,3,opt,name=connected,proto3" json:"connected,omitempty"`
	// The time since wireless activity last occurred.
	Inactive *durationpb.Duration `protobuf:"bytes,4,opt,name=inactive,proto3" json:"inactive,omitempty"`
	// The number of bytes received by this station.
	ReceivedBytes int64 `protobuf:"varint,5,opt,name=received_bytes,json=receivedBytes,proto3" json:"received_bytes,omitempty"`
	// The number of bytes transmitted by this station.
	TransmittedBytes int64 `protobuf:"varint,6,opt,name=transmitted_bytes,json=transmittedBytes,proto3" json:"transmitted_bytes,omitempty"`
	// The number of packets received by this station.
	ReceivedPackets int64 `protobuf:"varint,7,opt,name=received_packets,json=receivedPackets,proto3" json:"received_packets,omitempty"`
	// The number of packets transmitted by this station.
	TransmittedPackets int64 `protobuf:"varint,8,opt,name=transmitted_packets,json=transmittedPackets,proto3" json:"transmitted_packets,omitempty"`
	// The current data receive bitrate, in bits/second.
	ReceiveBitrate int64 `protobuf:"varint,9,opt,name=receive_bitrate,json=receiveBitrate,proto3" json:"receive_bitrate,omitempty"`
	// The current data transmit bitrate, in bits/second.
	TransmitBitrate int64 `protobuf:"varint,10,opt,name=transmit_bitrate,json=transmitBitrate,proto3" json:"transmit_bitrate,omitempty"`
	// The signal strength of the last received PPDU, in dBm.
	Signal int32 `protobuf:"varint,11,opt,name=signal,proto3" json:"signal,omitempty"`
	// The average signal strength, in dBm.
	SignalAverage int32 `protobuf:"varint,12,opt,name=signal_average,json=signalAverage,proto3" json:"signal_average,omitempty"`
	// The number of times the station has had to retry while sending a packet.
	TransmitRetries int64 `protobuf:"varint,13,opt,name=transmit_retries,json=transmitRetries,proto3" json:"transmit_retries,omitempty"`
	// The number of times a packet transmission failed.
	TransmitFailed int64 `protobuf:"varint,14,opt,name=transmit_failed,json=transmitFailed,proto3" json:"transmit_failed,omitempty"`
	// The number of times a beacon loss was detected.
	BeaconLoss    int64 `protobuf:"varint,15,opt,name=beacon_loss,json=beaconLoss,proto3" json:"beacon_loss,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StationInfo) Reset() {
	*x = StationInfo{}
	mi := &file_openmanet_service_v1_station_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StationInfo) ProtoMessage() {}

func (x *StationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_service_v1_station_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StationInfo.ProtoReflect.Descriptor instead.
func (*StationInfo) Descriptor() ([]byte, []int) {
	return file_openmanet_service_v1_station_proto_rawDescGZIP(), []int{0}
}

func (x *StationInfo) GetInterfaceIndex() int32 {
	if x != nil {
		return x.InterfaceIndex
	}
	return 0
}

func (x *StationInfo) GetHardwareAddress() string {
	if x != nil {
		return x.HardwareAddress
	}
	return ""
}

func (x *StationInfo) GetConnected() *durationpb.Duration {
	if x != nil {
		return x.Connected
	}
	return nil
}

func (x *StationInfo) GetInactive() *durationpb.Duration {
	if x != nil {
		return x.Inactive
	}
	return nil
}

func (x *StationInfo) GetReceivedBytes() int64 {
	if x != nil {
		return x.ReceivedBytes
	}
	return 0
}

func (x *StationInfo) GetTransmittedBytes() int64 {
	if x != nil {
		return x.TransmittedBytes
	}
	return 0
}

func (x *StationInfo) GetReceivedPackets() int64 {
	if x != nil {
		return x.ReceivedPackets
	}
	return 0
}

func (x *StationInfo) GetTransmittedPackets() int64 {
	if x != nil {
		return x.TransmittedPackets
	}
	return 0
}

func (x *StationInfo) GetReceiveBitrate() int64 {
	if x != nil {
		return x.ReceiveBitrate
	}
	return 0
}

func (x *StationInfo) GetTransmitBitrate() int64 {
	if x != nil {
		return x.TransmitBitrate
	}
	return 0
}

func (x *StationInfo) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

func (x *StationInfo) GetSignalAverage() int32 {
	if x != nil {
		return x.SignalAverage
	}
	return 0
}

func (x *StationInfo) GetTransmitRetries() int64 {
	if x != nil {
		return x.TransmitRetries
	}
	return 0
}

func (x *StationInfo) GetTransmitFailed() int64 {
	if x != nil {
		return x.TransmitFailed
	}
	return 0
}

func (x *StationInfo) GetBeaconLoss() int64 {
	if x != nil {
		return x.BeaconLoss
	}
	return 0
}

// Request message for listing stations.
type ListStationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: Filter stations by interface index.
	InterfaceIndex *int32 `protobuf:"varint,1,opt,name=interface_index,json=interfaceIndex,proto3,oneof" json:"interface_index,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListStationsRequest) Reset() {
	*x = ListStationsRequest{}
	mi := &file_openmanet_service_v1_station_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStationsRequest) ProtoMessage() {}

func (x *ListStationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_service_v1_station_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStationsRequest.ProtoReflect.Descriptor instead.
func (*ListStationsRequest) Descriptor() ([]byte, []int) {
	return file_openmanet_service_v1_station_proto_rawDescGZIP(), []int{1}
}

func (x *ListStationsRequest) GetInterfaceIndex() int32 {
	if x != nil && x.InterfaceIndex != nil {
		return *x.InterfaceIndex
	}
	return 0
}

// Response message containing a list of stations.
type ListStationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stations      []*StationInfo         `protobuf:"bytes,1,rep,name=stations,proto3" json:"stations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStationsResponse) Reset() {
	*x = ListStationsResponse{}
	mi := &file_openmanet_service_v1_station_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStationsResponse) ProtoMessage() {}

func (x *ListStationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_service_v1_station_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStationsResponse.ProtoReflect.Descriptor instead.
func (*ListStationsResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_service_v1_station_proto_rawDescGZIP(), []int{2}
}

func (x *ListStationsResponse) GetStations() []*StationInfo {
	if x != nil {
		return x.Stations
	}
	return nil
}

// Request message for getting a specific station.
type GetStationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The hardware address of the station to retrieve.
	HardwareAddress string `protobuf:"bytes,1,opt,name=hardware_address,json=hardwareAddress,proto3" json:"hardware_address,omitempty"`
	// Optional: The interface index to look up the station on.
	InterfaceIndex *int32 `protobuf:"varint,2,opt,name=interface_index,json=interfaceIndex,proto3,oneof" json:"interface_index,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStationRequest) Reset() {
	*x = GetStationRequest{}
	mi := &file_openmanet_service_v1_station_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStationRequest) ProtoMessage() {}

func (x *GetStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_service_v1_station_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStationRequest.ProtoReflect.Descriptor instead.
func (*GetStationRequest) Descriptor() ([]byte, []int) {
	return file_openmanet_service_v1_station_proto_rawDescGZIP(), []int{3}
}

func (x *GetStationRequest) GetHardwareAddress() string {
	if x != nil {
		return x.HardwareAddress
	}
	return ""
}

func (x *GetStationRequest) GetInterfaceIndex() int32 {
	if x != nil && x.InterfaceIndex != nil {
		return *x.InterfaceIndex
	}
	return 0
}

type GetStationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Station information
	Station       *StationInfo `protobuf:"bytes,1,opt,name=station,proto3" json:"station,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStationResponse) Reset() {
	*x = GetStationResponse{}
	mi := &file_openmanet_service_v1_station_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStationResponse) ProtoMessage() {}

func (x *GetStationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_service_v1_station_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStationResponse.ProtoReflect.Descriptor instead.
func (*GetStationResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_service_v1_station_proto_rawDescGZIP(), []int{4}
}

func (x *GetStationResponse) GetStation() *StationInfo {
	if x != nil {
		return x.Station
	}
	return nil
}

var File_openmanet_service_v1_station_proto protoreflect.FileDescriptor

const file_openmanet_service_v1_station_proto_rawDesc = "" +
	"\n" +
	"\"openmanet/service/v1/station.proto\x12\x14openmanet.service.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\"\x92\x05\n" +
	"\vStationInfo\x12'\n" +
	"\x0finterface_index\x18\x01 \x01(\x05R\x0einterfaceIndex\x122\n" +
	"\x10hardware_address\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0fhardwareAddress\x127\n" +
	"\tconnected\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\tconnected\x125\n" +
	"\binactive\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\binactive\x12%\n" +
	"\x0ereceived_bytes\x18\x05 \x01(\x03R\rreceivedBytes\x12+\n" +
	"\x11transmitted_bytes\x18\x06 \x01(\x03R\x10transmittedBytes\x12)\n" +
	"\x10received_packets\x18\a \x01(\x03R\x0freceivedPackets\x12/\n" +
	"\x13transmitted_packets\x18\b \x01(\x03R\x12transmittedPackets\x12'\n" +
	"\x0freceive_bitrate\x18\t \x01(\x03R\x0ereceiveBitrate\x12)\n" +
	"\x10transmit_bitrate\x18\n" +
	" \x01(\x03R\x0ftransmitBitrate\x12\x16\n" +
	"\x06signal\x18\v \x01(\x05R\x06signal\x12%\n" +
	"\x0esignal_average\x18\f \x01(\x05R\rsignalAverage\x12)\n" +
	"\x10transmit_retries\x18\r \x01(\x03R\x0ftransmitRetries\x12'\n" +
	"\x0ftransmit_failed\x18\x0e \x01(\x03R\x0etransmitFailed\x12\x1f\n" +
	"\vbeacon_loss\x18\x0f \x01(\x03R\n" +
	"beaconLoss\"W\n" +
	"\x13ListStationsRequest\x12,\n" +
	"\x0finterface_index\x18\x01 \x01(\x05H\x00R\x0einterfaceIndex\x88\x01\x01B\x12\n" +
	"\x10_interface_index\"U\n" +
	"\x14ListStationsResponse\x12=\n" +
	"\bstations\x18\x01 \x03(\v2!.openmanet.service.v1.StationInfoR\bstations\"\x89\x01\n" +
	"\x11GetStationRequest\x122\n" +
	"\x10hardware_address\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0fhardwareAddress\x12,\n" +
	"\x0finterface_index\x18\x02 \x01(\x05H\x00R\x0einterfaceIndex\x88\x01\x01B\x12\n" +
	"\x10_interface_index\"Q\n" +
	"\x12GetStationResponse\x12;\n" +
	"\astation\x18\x01 \x01(\v2!.openmanet.service.v1.StationInfoR\astation2\xd8\x01\n" +
	"\x0eStationService\x12e\n" +
	"\fListStations\x12).openmanet.service.v1.ListStationsRequest\x1a*.openmanet.service.v1.ListStationsResponse\x12_\n" +
	"\n" +
	"GetStation\x12'.openmanet.service.v1.GetStationRequest\x1a(.openmanet.service.v1.GetStationResponseB\xe7\x01\n" +
	"\x18com.openmanet.service.v1B\fStationProtoP\x01ZKgithub.com/openmanet/openmanetd/internal/api/openmanet/service/v1;servicev1\xa2\x02\x03OSX\xaa\x02\x14Openmanet.Service.V1\xca\x02\x14Openmanet\\Service\\V1\xe2\x02 Openmanet\\Service\\V1\\GPBMetadata\xea\x02\x16Openmanet::Service::V1b\x06proto3"

var (
	file_openmanet_service_v1_station_proto_rawDescOnce sync.Once
	file_openmanet_service_v1_station_proto_rawDescData []byte
)

func file_openmanet_service_v1_station_proto_rawDescGZIP() []byte {
	file_openmanet_service_v1_station_proto_rawDescOnce.Do(func() {
		file_openmanet_service_v1_station_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openmanet_service_v1_station_proto_rawDesc), len(file_openmanet_service_v1_station_proto_rawDesc)))
	})
	return file_openmanet_service_v1_station_proto_rawDescData
}

var file_openmanet_service_v1_station_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_openmanet_service_v1_station_proto_goTypes = []any{
	(*StationInfo)(nil),          // 0: openmanet.service.v1.StationInfo
	(*ListStationsRequest)(nil),  // 1: openmanet.service.v1.ListStationsRequest
	(*ListStationsResponse)(nil), // 2: openmanet.service.v1.ListStationsResponse
	(*GetStationRequest)(nil),    // 3: openmanet.service.v1.GetStationRequest
	(*GetStationResponse)(nil),   // 4: openmanet.service.v1.GetStationResponse
	(*durationpb.Duration)(nil),  // 5: google.protobuf.Duration
}
var file_openmanet_service_v1_station_proto_depIdxs = []int32{
	5, // 0: openmanet.service.v1.StationInfo.connected:type_name -> google.protobuf.Duration
	5, // 1: openmanet.service.v1.StationInfo.inactive:type_name -> google.protobuf.Duration
	0, // 2: openmanet.service.v1.ListStationsResponse.stations:type_name -> openmanet.service.v1.StationInfo
	0, // 3: openmanet.service.v1.GetStationResponse.station:type_name -> openmanet.service.v1.StationInfo
	1, // 4: openmanet.service.v1.StationService.ListStations:input_type -> openmanet.service.v1.ListStationsRequest
	3, // 5: openmanet.service.v1.StationService.GetStation:input_type -> openmanet.service.v1.GetStationRequest
	2, // 6: openmanet.service.v1.StationService.ListStations:output_type -> openmanet.service.v1.ListStationsResponse
	4, // 7: openmanet.service.v1.StationService.GetStation:output_type -> openmanet.service.v1.GetStationResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_openmanet_service_v1_station_proto_init() }
func file_openmanet_service_v1_station_proto_init() {
	if File_openmanet_service_v1_station_proto != nil {
		return
	}
	file_openmanet_service_v1_station_proto_msgTypes[1].OneofWrappers = []any{}
	file_openmanet_service_v1_station_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmanet_service_v1_station_proto_rawDesc), len(file_openmanet_service_v1_station_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openmanet_service_v1_station_proto_goTypes,
		DependencyIndexes: file_openmanet_service_v1_station_proto_depIdxs,
		MessageInfos:      file_openmanet_service_v1_station_proto_msgTypes,
	}.Build()
	File_openmanet_service_v1_station_proto = out.File
	file_openmanet_service_v1_station_proto_goTypes = nil
	file_openmanet_service_v1_station_proto_depIdxs = nil
}
