// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: openmanet/wifi_config/v1/wifi_config_service.proto

package wifi_configv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/openmanet/openmanetd/internal/api/openmanet/wifi_config/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WifiConfigServiceName is the fully-qualified name of the WifiConfigService service.
	WifiConfigServiceName = "openmanet.wifi_config.v1.WifiConfigService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WifiConfigServiceListRadiosProcedure is the fully-qualified name of the WifiConfigService's
	// ListRadios RPC.
	WifiConfigServiceListRadiosProcedure = "/openmanet.wifi_config.v1.WifiConfigService/ListRadios"
	// WifiConfigServiceGetRadioStatusProcedure is the fully-qualified name of the WifiConfigService's
	// GetRadioStatus RPC.
	WifiConfigServiceGetRadioStatusProcedure = "/openmanet.wifi_config.v1.WifiConfigService/GetRadioStatus"
	// WifiConfigServiceGetRadioSettingsProcedure is the fully-qualified name of the WifiConfigService's
	// GetRadioSettings RPC.
	WifiConfigServiceGetRadioSettingsProcedure = "/openmanet.wifi_config.v1.WifiConfigService/GetRadioSettings"
	// WifiConfigServiceUpdateRadioSettingsProcedure is the fully-qualified name of the
	// WifiConfigService's UpdateRadioSettings RPC.
	WifiConfigServiceUpdateRadioSettingsProcedure = "/openmanet.wifi_config.v1.WifiConfigService/UpdateRadioSettings"
	// WifiConfigServiceListConnectedClientsProcedure is the fully-qualified name of the
	// WifiConfigService's ListConnectedClients RPC.
	WifiConfigServiceListConnectedClientsProcedure = "/openmanet.wifi_config.v1.WifiConfigService/ListConnectedClients"
	// WifiConfigServiceListMeshPeersProcedure is the fully-qualified name of the WifiConfigService's
	// ListMeshPeers RPC.
	WifiConfigServiceListMeshPeersProcedure = "/openmanet.wifi_config.v1.WifiConfigService/ListMeshPeers"
)

// WifiConfigServiceClient is a client for the openmanet.wifi_config.v1.WifiConfigService service.
type WifiConfigServiceClient interface {
	// ListRadios returns all physical radios available on the device.
	ListRadios(context.Context, *emptypb.Empty) (*v1.ListRadiosResponse, error)
	// GetRadioStatus returns the current runtime status for a specific radio.
	GetRadioStatus(context.Context, *v1.GetRadioStatusRequest) (*v1.GetRadioStatusResponse, error)
	// GetRadioSettings returns the editable configuration for a specific radio,
	// along with lists of valid options for drop-down menus.
	GetRadioSettings(context.Context, *v1.GetRadioSettingsRequest) (*v1.GetRadioSettingsResponse, error)
	// UpdateRadioSettings applies new configuration to a radio. The changes are
	// committed and the wireless subsystem is reloaded.
	UpdateRadioSettings(context.Context, *v1.UpdateRadioSettingsRequest) (*v1.UpdateRadioSettingsResponse, error)
	// ListConnectedClients returns all clients connected to an AP-mode radio.
	ListConnectedClients(context.Context, *v1.ListConnectedClientsRequest) (*v1.ListConnectedClientsResponse, error)
	// ListMeshPeers returns all mesh peers visible to a mesh-mode radio.
	ListMeshPeers(context.Context, *v1.ListMeshPeersRequest) (*v1.ListMeshPeersResponse, error)
}

// NewWifiConfigServiceClient constructs a client for the openmanet.wifi_config.v1.WifiConfigService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWifiConfigServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WifiConfigServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	wifiConfigServiceMethods := v1.File_openmanet_wifi_config_v1_wifi_config_service_proto.Services().ByName("WifiConfigService").Methods()
	return &wifiConfigServiceClient{
		listRadios: connect.NewClient[emptypb.Empty, v1.ListRadiosResponse](
			httpClient,
			baseURL+WifiConfigServiceListRadiosProcedure,
			connect.WithSchema(wifiConfigServiceMethods.ByName("ListRadios")),
			connect.WithClientOptions(opts...),
		),
		getRadioStatus: connect.NewClient[v1.GetRadioStatusRequest, v1.GetRadioStatusResponse](
			httpClient,
			baseURL+WifiConfigServiceGetRadioStatusProcedure,
			connect.WithSchema(wifiConfigServiceMethods.ByName("GetRadioStatus")),
			connect.WithClientOptions(opts...),
		),
		getRadioSettings: connect.NewClient[v1.GetRadioSettingsRequest, v1.GetRadioSettingsResponse](
			httpClient,
			baseURL+WifiConfigServiceGetRadioSettingsProcedure,
			connect.WithSchema(wifiConfigServiceMethods.ByName("GetRadioSettings")),
			connect.WithClientOptions(opts...),
		),
		updateRadioSettings: connect.NewClient[v1.UpdateRadioSettingsRequest, v1.UpdateRadioSettingsResponse](
			httpClient,
			baseURL+WifiConfigServiceUpdateRadioSettingsProcedure,
			connect.WithSchema(wifiConfigServiceMethods.ByName("UpdateRadioSettings")),
			connect.WithClientOptions(opts...),
		),
		listConnectedClients: connect.NewClient[v1.ListConnectedClientsRequest, v1.ListConnectedClientsResponse](
			httpClient,
			baseURL+WifiConfigServiceListConnectedClientsProcedure,
			connect.WithSchema(wifiConfigServiceMethods.ByName("ListConnectedClients")),
			connect.WithClientOptions(opts...),
		),
		listMeshPeers: connect.NewClient[v1.ListMeshPeersRequest, v1.ListMeshPeersResponse](
			httpClient,
			baseURL+WifiConfigServiceListMeshPeersProcedure,
			connect.WithSchema(wifiConfigServiceMethods.ByName("ListMeshPeers")),
			connect.WithClientOptions(opts...),
		),
	}
}

// wifiConfigServiceClient implements WifiConfigServiceClient.
type wifiConfigServiceClient struct {
	listRadios           *connect.Client[emptypb.Empty, v1.ListRadiosResponse]
	getRadioStatus       *connect.Client[v1.GetRadioStatusRequest, v1.GetRadioStatusResponse]
	getRadioSettings     *connect.Client[v1.GetRadioSettingsRequest, v1.GetRadioSettingsResponse]
	updateRadioSettings  *connect.Client[v1.UpdateRadioSettingsRequest, v1.UpdateRadioSettingsResponse]
	listConnectedClients *connect.Client[v1.ListConnectedClientsRequest, v1.ListConnectedClientsResponse]
	listMeshPeers        *connect.Client[v1.ListMeshPeersRequest, v1.ListMeshPeersResponse]
}

// ListRadios calls openmanet.wifi_config.v1.WifiConfigService.ListRadios.
func (c *wifiConfigServiceClient) ListRadios(ctx context.Context, req *emptypb.Empty) (*v1.ListRadiosResponse, error) {
	response, err := c.listRadios.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetRadioStatus calls openmanet.wifi_config.v1.WifiConfigService.GetRadioStatus.
func (c *wifiConfigServiceClient) GetRadioStatus(ctx context.Context, req *v1.GetRadioStatusRequest) (*v1.GetRadioStatusResponse, error) {
	response, err := c.getRadioStatus.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetRadioSettings calls openmanet.wifi_config.v1.WifiConfigService.GetRadioSettings.
func (c *wifiConfigServiceClient) GetRadioSettings(ctx context.Context, req *v1.GetRadioSettingsRequest) (*v1.GetRadioSettingsResponse, error) {
	response, err := c.getRadioSettings.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateRadioSettings calls openmanet.wifi_config.v1.WifiConfigService.UpdateRadioSettings.
func (c *wifiConfigServiceClient) UpdateRadioSettings(ctx context.Context, req *v1.UpdateRadioSettingsRequest) (*v1.UpdateRadioSettingsResponse, error) {
	response, err := c.updateRadioSettings.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListConnectedClients calls openmanet.wifi_config.v1.WifiConfigService.ListConnectedClients.
func (c *wifiConfigServiceClient) ListConnectedClients(ctx context.Context, req *v1.ListConnectedClientsRequest) (*v1.ListConnectedClientsResponse, error) {
	response, err := c.listConnectedClients.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListMeshPeers calls openmanet.wifi_config.v1.WifiConfigService.ListMeshPeers.
func (c *wifiConfigServiceClient) ListMeshPeers(ctx context.Context, req *v1.ListMeshPeersRequest) (*v1.ListMeshPeersResponse, error) {
	response, err := c.listMeshPeers.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// WifiConfigServiceHandler is an implementation of the openmanet.wifi_config.v1.WifiConfigService
// service.
type WifiConfigServiceHandler interface {
	// ListRadios returns all physical radios available on the device.
	ListRadios(context.Context, *emptypb.Empty) (*v1.ListRadiosResponse, error)
	// GetRadioStatus returns the current runtime status for a specific radio.
	GetRadioStatus(context.Context, *v1.GetRadioStatusRequest) (*v1.GetRadioStatusResponse, error)
	// GetRadioSettings returns the editable configuration for a specific radio,
	// along with lists of valid options for drop-down menus.
	GetRadioSettings(context.Context, *v1.GetRadioSettingsRequest) (*v1.GetRadioSettingsResponse, error)
	// UpdateRadioSettings applies new configuration to a radio. The changes are
	// committed and the wireless subsystem is reloaded.
	UpdateRadioSettings(context.Context, *v1.UpdateRadioSettingsRequest) (*v1.UpdateRadioSettingsResponse, error)
	// ListConnectedClients returns all clients connected to an AP-mode radio.
	ListConnectedClients(context.Context, *v1.ListConnectedClientsRequest) (*v1.ListConnectedClientsResponse, error)
	// ListMeshPeers returns all mesh peers visible to a mesh-mode radio.
	ListMeshPeers(context.Context, *v1.ListMeshPeersRequest) (*v1.ListMeshPeersResponse, error)
}

// NewWifiConfigServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWifiConfigServiceHandler(svc WifiConfigServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	wifiConfigServiceMethods := v1.File_openmanet_wifi_config_v1_wifi_config_service_proto.Services().ByName("WifiConfigService").Methods()
	wifiConfigServiceListRadiosHandler := connect.NewUnaryHandlerSimple(
		WifiConfigServiceListRadiosProcedure,
		svc.ListRadios,
		connect.WithSchema(wifiConfigServiceMethods.ByName("ListRadios")),
		connect.WithHandlerOptions(opts...),
	)
	wifiConfigServiceGetRadioStatusHandler := connect.NewUnaryHandlerSimple(
		WifiConfigServiceGetRadioStatusProcedure,
		svc.GetRadioStatus,
		connect.WithSchema(wifiConfigServiceMethods.ByName("GetRadioStatus")),
		connect.WithHandlerOptions(opts...),
	)
	wifiConfigServiceGetRadioSettingsHandler := connect.NewUnaryHandlerSimple(
		WifiConfigServiceGetRadioSettingsProcedure,
		svc.GetRadioSettings,
		connect.WithSchema(wifiConfigServiceMethods.ByName("GetRadioSettings")),
		connect.WithHandlerOptions(opts...),
	)
	wifiConfigServiceUpdateRadioSettingsHandler := connect.NewUnaryHandlerSimple(
		WifiConfigServiceUpdateRadioSettingsProcedure,
		svc.UpdateRadioSettings,
		connect.WithSchema(wifiConfigServiceMethods.ByName("UpdateRadioSettings")),
		connect.WithHandlerOptions(opts...),
	)
	wifiConfigServiceListConnectedClientsHandler := connect.NewUnaryHandlerSimple(
		WifiConfigServiceListConnectedClientsProcedure,
		svc.ListConnectedClients,
		connect.WithSchema(wifiConfigServiceMethods.ByName("ListConnectedClients")),
		connect.WithHandlerOptions(opts...),
	)
	wifiConfigServiceListMeshPeersHandler := connect.NewUnaryHandlerSimple(
		WifiConfigServiceListMeshPeersProcedure,
		svc.ListMeshPeers,
		connect.WithSchema(wifiConfigServiceMethods.ByName("ListMeshPeers")),
		connect.WithHandlerOptions(opts...),
	)
	return "/openmanet.wifi_config.v1.WifiConfigService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WifiConfigServiceListRadiosProcedure:
			wifiConfigServiceListRadiosHandler.ServeHTTP(w, r)
		case WifiConfigServiceGetRadioStatusProcedure:
			wifiConfigServiceGetRadioStatusHandler.ServeHTTP(w, r)
		case WifiConfigServiceGetRadioSettingsProcedure:
			wifiConfigServiceGetRadioSettingsHandler.ServeHTTP(w, r)
		case WifiConfigServiceUpdateRadioSettingsProcedure:
			wifiConfigServiceUpdateRadioSettingsHandler.ServeHTTP(w, r)
		case WifiConfigServiceListConnectedClientsProcedure:
			wifiConfigServiceListConnectedClientsHandler.ServeHTTP(w, r)
		case WifiConfigServiceListMeshPeersProcedure:
			wifiConfigServiceListMeshPeersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWifiConfigServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWifiConfigServiceHandler struct{}

func (UnimplementedWifiConfigServiceHandler) ListRadios(context.Context, *emptypb.Empty) (*v1.ListRadiosResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.wifi_config.v1.WifiConfigService.ListRadios is not implemented"))
}

func (UnimplementedWifiConfigServiceHandler) GetRadioStatus(context.Context, *v1.GetRadioStatusRequest) (*v1.GetRadioStatusResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.wifi_config.v1.WifiConfigService.GetRadioStatus is not implemented"))
}

func (UnimplementedWifiConfigServiceHandler) GetRadioSettings(context.Context, *v1.GetRadioSettingsRequest) (*v1.GetRadioSettingsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.wifi_config.v1.WifiConfigService.GetRadioSettings is not implemented"))
}

func (UnimplementedWifiConfigServiceHandler) UpdateRadioSettings(context.Context, *v1.UpdateRadioSettingsRequest) (*v1.UpdateRadioSettingsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.wifi_config.v1.WifiConfigService.UpdateRadioSettings is not implemented"))
}

func (UnimplementedWifiConfigServiceHandler) ListConnectedClients(context.Context, *v1.ListConnectedClientsRequest) (*v1.ListConnectedClientsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.wifi_config.v1.WifiConfigService.ListConnectedClients is not implemented"))
}

func (UnimplementedWifiConfigServiceHandler) ListMeshPeers(context.Context, *v1.ListMeshPeersRequest) (*v1.ListMeshPeersResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.wifi_config.v1.WifiConfigService.ListMeshPeers is not implemented"))
}
