// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.0
// source: openmanet/gnss/v1/gnss_service.proto

package gnssv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GNSSServiceClient is the client API for GNSSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GNSSServiceClient interface {
	// GetGNSSStatus returns the current GPS position fix and a snapshot of the
	// satellite constellation visible to the receiver. The response includes
	// individual satellite details (PRN, elevation, azimuth, SNR, and whether
	// the satellite is used in the navigation solution) as well as aggregate
	// dilution-of-precision metrics (PDOP, HDOP).
	//
	// Returns an empty response (not an error) when the GNSS subsystem is
	// disabled or the receiver hardware is not present.
	GetGNSSStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetGNSSStatusResponse, error)
	// GetGNSSConfig returns the current GNSS receiver settings and output
	// protocol configuration as stored in the persistent config file. This
	// includes the enable/disable state, NMEA and CoT distribution toggles,
	// and the CoT UID.
	GetGNSSConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetGNSSConfigResponse, error)
	// UpdateGNSSConfig persists the provided GNSS settings and output protocol
	// configuration to the config file and refreshes the in-memory state.
	// Changes take effect immediately for output protocol toggles; enabling or
	// disabling the GNSS receiver itself may require a service restart.
	//
	// Returns a CodeInternal error if the config file cannot be written.
	UpdateGNSSConfig(ctx context.Context, in *UpdateGNSSConfigRequest, opts ...grpc.CallOption) (*UpdateGNSSConfigResponse, error)
}

type gNSSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGNSSServiceClient(cc grpc.ClientConnInterface) GNSSServiceClient {
	return &gNSSServiceClient{cc}
}

func (c *gNSSServiceClient) GetGNSSStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetGNSSStatusResponse, error) {
	out := new(GetGNSSStatusResponse)
	err := c.cc.Invoke(ctx, "/openmanet.gnss.v1.GNSSService/GetGNSSStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNSSServiceClient) GetGNSSConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetGNSSConfigResponse, error) {
	out := new(GetGNSSConfigResponse)
	err := c.cc.Invoke(ctx, "/openmanet.gnss.v1.GNSSService/GetGNSSConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNSSServiceClient) UpdateGNSSConfig(ctx context.Context, in *UpdateGNSSConfigRequest, opts ...grpc.CallOption) (*UpdateGNSSConfigResponse, error) {
	out := new(UpdateGNSSConfigResponse)
	err := c.cc.Invoke(ctx, "/openmanet.gnss.v1.GNSSService/UpdateGNSSConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GNSSServiceServer is the server API for GNSSService service.
// All implementations must embed UnimplementedGNSSServiceServer
// for forward compatibility
type GNSSServiceServer interface {
	// GetGNSSStatus returns the current GPS position fix and a snapshot of the
	// satellite constellation visible to the receiver. The response includes
	// individual satellite details (PRN, elevation, azimuth, SNR, and whether
	// the satellite is used in the navigation solution) as well as aggregate
	// dilution-of-precision metrics (PDOP, HDOP).
	//
	// Returns an empty response (not an error) when the GNSS subsystem is
	// disabled or the receiver hardware is not present.
	GetGNSSStatus(context.Context, *emptypb.Empty) (*GetGNSSStatusResponse, error)
	// GetGNSSConfig returns the current GNSS receiver settings and output
	// protocol configuration as stored in the persistent config file. This
	// includes the enable/disable state, NMEA and CoT distribution toggles,
	// and the CoT UID.
	GetGNSSConfig(context.Context, *emptypb.Empty) (*GetGNSSConfigResponse, error)
	// UpdateGNSSConfig persists the provided GNSS settings and output protocol
	// configuration to the config file and refreshes the in-memory state.
	// Changes take effect immediately for output protocol toggles; enabling or
	// disabling the GNSS receiver itself may require a service restart.
	//
	// Returns a CodeInternal error if the config file cannot be written.
	UpdateGNSSConfig(context.Context, *UpdateGNSSConfigRequest) (*UpdateGNSSConfigResponse, error)
	mustEmbedUnimplementedGNSSServiceServer()
}

// UnimplementedGNSSServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGNSSServiceServer struct {
}

func (UnimplementedGNSSServiceServer) GetGNSSStatus(context.Context, *emptypb.Empty) (*GetGNSSStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGNSSStatus not implemented")
}
func (UnimplementedGNSSServiceServer) GetGNSSConfig(context.Context, *emptypb.Empty) (*GetGNSSConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGNSSConfig not implemented")
}
func (UnimplementedGNSSServiceServer) UpdateGNSSConfig(context.Context, *UpdateGNSSConfigRequest) (*UpdateGNSSConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGNSSConfig not implemented")
}
func (UnimplementedGNSSServiceServer) mustEmbedUnimplementedGNSSServiceServer() {}

// UnsafeGNSSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GNSSServiceServer will
// result in compilation errors.
type UnsafeGNSSServiceServer interface {
	mustEmbedUnimplementedGNSSServiceServer()
}

func RegisterGNSSServiceServer(s grpc.ServiceRegistrar, srv GNSSServiceServer) {
	s.RegisterService(&GNSSService_ServiceDesc, srv)
}

func _GNSSService_GetGNSSStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNSSServiceServer).GetGNSSStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.gnss.v1.GNSSService/GetGNSSStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNSSServiceServer).GetGNSSStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNSSService_GetGNSSConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNSSServiceServer).GetGNSSConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.gnss.v1.GNSSService/GetGNSSConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNSSServiceServer).GetGNSSConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNSSService_UpdateGNSSConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGNSSConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNSSServiceServer).UpdateGNSSConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.gnss.v1.GNSSService/UpdateGNSSConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNSSServiceServer).UpdateGNSSConfig(ctx, req.(*UpdateGNSSConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GNSSService_ServiceDesc is the grpc.ServiceDesc for GNSSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GNSSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openmanet.gnss.v1.GNSSService",
	HandlerType: (*GNSSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGNSSStatus",
			Handler:    _GNSSService_GetGNSSStatus_Handler,
		},
		{
			MethodName: "GetGNSSConfig",
			Handler:    _GNSSService_GetGNSSConfig_Handler,
		},
		{
			MethodName: "UpdateGNSSConfig",
			Handler:    _GNSSService_UpdateGNSSConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openmanet/gnss/v1/gnss_service.proto",
}
