// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openmanet/gnss/v1/gnss.proto

package gnssv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FixType describes the type of GPS navigation fix currently obtained by the
// receiver. The fix type determines which position dimensions are valid.
type FixType int32

const (
	// FIX_TYPE_UNSPECIFIED indicates the fix type has not been determined.
	FixType_FIX_TYPE_UNSPECIFIED FixType = 0
	// FIX_TYPE_NO_FIX indicates that the receiver has not acquired a valid
	// position fix. Position coordinates should be considered invalid.
	FixType_FIX_TYPE_NO_FIX FixType = 1
	// FIX_TYPE_2D indicates a two-dimensional fix. Latitude and longitude are
	// valid, but altitude is not reliably determined.
	FixType_FIX_TYPE_2D FixType = 2
	// FIX_TYPE_3D indicates a three-dimensional fix. Latitude, longitude, and
	// altitude are all valid.
	FixType_FIX_TYPE_3D FixType = 3
)

// Enum value maps for FixType.
var (
	FixType_name = map[int32]string{
		0: "FIX_TYPE_UNSPECIFIED",
		1: "FIX_TYPE_NO_FIX",
		2: "FIX_TYPE_2D",
		3: "FIX_TYPE_3D",
	}
	FixType_value = map[string]int32{
		"FIX_TYPE_UNSPECIFIED": 0,
		"FIX_TYPE_NO_FIX":      1,
		"FIX_TYPE_2D":          2,
		"FIX_TYPE_3D":          3,
	}
)

func (x FixType) Enum() *FixType {
	p := new(FixType)
	*p = x
	return p
}

func (x FixType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FixType) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_gnss_v1_gnss_proto_enumTypes[0].Descriptor()
}

func (FixType) Type() protoreflect.EnumType {
	return &file_openmanet_gnss_v1_gnss_proto_enumTypes[0]
}

func (x FixType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FixType.Descriptor instead.
func (FixType) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_gnss_v1_gnss_proto_rawDescGZIP(), []int{0}
}

// Constellation identifies the GNSS satellite system that emitted a signal.
// Values match gpsd's gnssid encoding; UNSPECIFIED is reported for any
// constellation the daemon could not identify.
type Constellation int32

const (
	Constellation_CONSTELLATION_UNSPECIFIED Constellation = 0
	Constellation_CONSTELLATION_GPS         Constellation = 1
	Constellation_CONSTELLATION_SBAS        Constellation = 2
	Constellation_CONSTELLATION_GALILEO     Constellation = 3
	Constellation_CONSTELLATION_BEIDOU      Constellation = 4
	Constellation_CONSTELLATION_IMES        Constellation = 5
	Constellation_CONSTELLATION_QZSS        Constellation = 6
	Constellation_CONSTELLATION_GLONASS     Constellation = 7
	Constellation_CONSTELLATION_IRNSS       Constellation = 8
)

// Enum value maps for Constellation.
var (
	Constellation_name = map[int32]string{
		0: "CONSTELLATION_UNSPECIFIED",
		1: "CONSTELLATION_GPS",
		2: "CONSTELLATION_SBAS",
		3: "CONSTELLATION_GALILEO",
		4: "CONSTELLATION_BEIDOU",
		5: "CONSTELLATION_IMES",
		6: "CONSTELLATION_QZSS",
		7: "CONSTELLATION_GLONASS",
		8: "CONSTELLATION_IRNSS",
	}
	Constellation_value = map[string]int32{
		"CONSTELLATION_UNSPECIFIED": 0,
		"CONSTELLATION_GPS":         1,
		"CONSTELLATION_SBAS":        2,
		"CONSTELLATION_GALILEO":     3,
		"CONSTELLATION_BEIDOU":      4,
		"CONSTELLATION_IMES":        5,
		"CONSTELLATION_QZSS":        6,
		"CONSTELLATION_GLONASS":     7,
		"CONSTELLATION_IRNSS":       8,
	}
)

func (x Constellation) Enum() *Constellation {
	p := new(Constellation)
	*p = x
	return p
}

func (x Constellation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Constellation) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_gnss_v1_gnss_proto_enumTypes[1].Descriptor()
}

func (Constellation) Type() protoreflect.EnumType {
	return &file_openmanet_gnss_v1_gnss_proto_enumTypes[1]
}

func (x Constellation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Constellation.Descriptor instead.
func (Constellation) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_gnss_v1_gnss_proto_rawDescGZIP(), []int{1}
}

// GNSSSource identifies which position provider feeds the GNSS subsystem.
type GNSSSource int32

const (
	// GNSS_SOURCE_UNSPECIFIED is treated as GNSS_SOURCE_INTERNAL.
	GNSSSource_GNSS_SOURCE_UNSPECIFIED GNSSSource = 0
	// GNSS_SOURCE_INTERNAL uses the position reported by the local GNSS
	// receiver via gpsd (onboard or USB-attached hardware).
	GNSSSource_GNSS_SOURCE_INTERNAL GNSSSource = 1
	// GNSS_SOURCE_EXTERNAL_COT adopts the position broadcast by a connected
	// end-user device (e.g. ATAK) as Cursor-on-Target over the SA multicast
	// group, instead of reading a local receiver. Lets a node with no GNSS
	// hardware still report its own position, using the EUD's (typically
	// more accurate) fix.
	GNSSSource_GNSS_SOURCE_EXTERNAL_COT GNSSSource = 2
)

// Enum value maps for GNSSSource.
var (
	GNSSSource_name = map[int32]string{
		0: "GNSS_SOURCE_UNSPECIFIED",
		1: "GNSS_SOURCE_INTERNAL",
		2: "GNSS_SOURCE_EXTERNAL_COT",
	}
	GNSSSource_value = map[string]int32{
		"GNSS_SOURCE_UNSPECIFIED":  0,
		"GNSS_SOURCE_INTERNAL":     1,
		"GNSS_SOURCE_EXTERNAL_COT": 2,
	}
)

func (x GNSSSource) Enum() *GNSSSource {
	p := new(GNSSSource)
	*p = x
	return p
}

func (x GNSSSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GNSSSource) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_gnss_v1_gnss_proto_enumTypes[2].Descriptor()
}

func (GNSSSource) Type() protoreflect.EnumType {
	return &file_openmanet_gnss_v1_gnss_proto_enumTypes[2]
}

func (x GNSSSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GNSSSource.Descriptor instead.
func (GNSSSource) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_gnss_v1_gnss_proto_rawDescGZIP(), []int{2}
}

// Position holds the current GPS position, motion vector, and accuracy
// metrics as reported by the GNSS receiver.
type Position struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// fix_type indicates the current navigation fix quality (none, 2D, or 3D).
	FixType FixType `protobuf:"varint,1,opt,name=fix_type,json=fixType,proto3,enum=openmanet.gnss.v1.FixType" json:"fix_type,omitempty"`
	// latitude is the WGS-84 latitude in decimal degrees. Positive values
	// indicate north of the equator; negative values indicate south.
	Latitude float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// longitude is the WGS-84 longitude in decimal degrees. Positive values
	// indicate east of the prime meridian; negative values indicate west.
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// altitude is the height above mean sea level (MSL) in meters.
	// Only meaningful when fix_type is FIX_TYPE_3D.
	Altitude float64 `protobuf:"fixed64,4,opt,name=altitude,proto3" json:"altitude,omitempty"`
	// speed is the ground speed in meters per second as reported by the
	// receiver's velocity solution.
	Speed float64 `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`
	// heading is the course over ground (true north reference) in degrees,
	// ranging from 0 to 360.
	Heading float64 `protobuf:"fixed64,6,opt,name=heading,proto3" json:"heading,omitempty"`
	// pdop is the Position Dilution of Precision, a unitless factor that
	// combines horizontal and vertical geometric dilution. Lower values
	// indicate better position accuracy.
	Pdop float64 `protobuf:"fixed64,7,opt,name=pdop,proto3" json:"pdop,omitempty"`
	// hdop is the Horizontal Dilution of Precision, a unitless factor
	// describing the geometric quality of the satellite constellation for
	// horizontal positioning. Lower values indicate better accuracy.
	Hdop float64 `protobuf:"fixed64,8,opt,name=hdop,proto3" json:"hdop,omitempty"`
	// last_update is the UTC timestamp of the most recent valid position fix
	// from the GNSS receiver.
	LastUpdate    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_openmanet_gnss_v1_gnss_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetFixType() FixType {
	if x != nil {
		return x.FixType
	}
	return FixType_FIX_TYPE_UNSPECIFIED
}

func (x *Position) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Position) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Position) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *Position) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Position) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *Position) GetPdop() float64 {
	if x != nil {
		return x.Pdop
	}
	return 0
}

func (x *Position) GetHdop() float64 {
	if x != nil {
		return x.Hdop
	}
	return 0
}

func (x *Position) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

// Satellite describes a single GNSS satellite currently visible to the
// receiver, including its orbital position, signal quality, and whether it
// is actively contributing to the navigation solution.
type Satellite struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// prn is the Pseudo-Random Noise code number that uniquely identifies the
	// satellite within its constellation (e.g., GPS PRN 1-32, GLONASS 65-96).
	Prn int32 `protobuf:"varint,1,opt,name=prn,proto3" json:"prn,omitempty"`
	// elevation is the satellite's angle above the local horizon in degrees,
	// ranging from 0 (on the horizon) to 90 (directly overhead).
	Elevation float64 `protobuf:"fixed64,2,opt,name=elevation,proto3" json:"elevation,omitempty"`
	// azimuth is the satellite's compass bearing from the receiver in degrees,
	// measured clockwise from true north (0-360).
	Azimuth float64 `protobuf:"fixed64,3,opt,name=azimuth,proto3" json:"azimuth,omitempty"`
	// snr is the carrier-to-noise density ratio (signal-to-noise ratio) in
	// dB-Hz. Higher values indicate a stronger, more reliable signal.
	// Typical range is 0-50 dB-Hz.
	Snr float64 `protobuf:"fixed64,4,opt,name=snr,proto3" json:"snr,omitempty"`
	// used indicates whether this satellite is currently included in the
	// receiver's navigation solution.
	Used bool `protobuf:"varint,5,opt,name=used,proto3" json:"used,omitempty"`
	// constellation identifies the GNSS system this satellite belongs to.
	// CONSTELLATION_UNSPECIFIED is emitted by older receivers or by gpsd
	// builds that do not propagate the gnssid field.
	Constellation Constellation `protobuf:"varint,6,opt,name=constellation,proto3,enum=openmanet.gnss.v1.Constellation" json:"constellation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Satellite) Reset() {
	*x = Satellite{}
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Satellite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Satellite) ProtoMessage() {}

func (x *Satellite) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Satellite.ProtoReflect.Descriptor instead.
func (*Satellite) Descriptor() ([]byte, []int) {
	return file_openmanet_gnss_v1_gnss_proto_rawDescGZIP(), []int{1}
}

func (x *Satellite) GetPrn() int32 {
	if x != nil {
		return x.Prn
	}
	return 0
}

func (x *Satellite) GetElevation() float64 {
	if x != nil {
		return x.Elevation
	}
	return 0
}

func (x *Satellite) GetAzimuth() float64 {
	if x != nil {
		return x.Azimuth
	}
	return 0
}

func (x *Satellite) GetSnr() float64 {
	if x != nil {
		return x.Snr
	}
	return 0
}

func (x *Satellite) GetUsed() bool {
	if x != nil {
		return x.Used
	}
	return false
}

func (x *Satellite) GetConstellation() Constellation {
	if x != nil {
		return x.Constellation
	}
	return Constellation_CONSTELLATION_UNSPECIFIED
}

// SatelliteStatus provides an overview of the GNSS satellite constellation
// as seen by the receiver, including summary counts and per-satellite detail.
type SatelliteStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// satellites_used is the number of satellites actively contributing to the
	// current navigation solution.
	SatellitesUsed int32 `protobuf:"varint,1,opt,name=satellites_used,json=satellitesUsed,proto3" json:"satellites_used,omitempty"`
	// satellites_in_view is the total number of satellites for which the
	// receiver is tracking signals, whether or not they are used in the
	// navigation solution.
	SatellitesInView int32 `protobuf:"varint,2,opt,name=satellites_in_view,json=satellitesInView,proto3" json:"satellites_in_view,omitempty"`
	// satellites contains detailed information for each satellite currently
	// visible to the receiver.
	Satellites []*Satellite `protobuf:"bytes,3,rep,name=satellites,proto3" json:"satellites,omitempty"`
	// last_update is the UTC timestamp of the most recent SKY report that
	// carried constellation detail. Partial SKY reports that only refresh
	// DOP values do not advance this timestamp, so it reflects the freshness
	// of the sky-in-view data rather than liveness of the gpsd link.
	LastUpdate    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatelliteStatus) Reset() {
	*x = SatelliteStatus{}
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatelliteStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteStatus) ProtoMessage() {}

func (x *SatelliteStatus) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteStatus.ProtoReflect.Descriptor instead.
func (*SatelliteStatus) Descriptor() ([]byte, []int) {
	return file_openmanet_gnss_v1_gnss_proto_rawDescGZIP(), []int{2}
}

func (x *SatelliteStatus) GetSatellitesUsed() int32 {
	if x != nil {
		return x.SatellitesUsed
	}
	return 0
}

func (x *SatelliteStatus) GetSatellitesInView() int32 {
	if x != nil {
		return x.SatellitesInView
	}
	return 0
}

func (x *SatelliteStatus) GetSatellites() []*Satellite {
	if x != nil {
		return x.Satellites
	}
	return nil
}

func (x *SatelliteStatus) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

// GNSSSettings holds the top-level GNSS receiver configuration that
// controls whether the GPS subsystem is active and where its position
// data comes from.
type GNSSSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// enable_gps controls whether the GNSS receiver subsystem is active.
	// When false, no position data is collected or distributed.
	EnableGps bool `protobuf:"varint,1,opt,name=enable_gps,json=enableGps,proto3" json:"enable_gps,omitempty"`
	// source selects which position provider feeds the GNSS subsystem.
	// GNSS_SOURCE_UNSPECIFIED is treated as GNSS_SOURCE_INTERNAL.
	Source        GNSSSource `protobuf:"varint,2,opt,name=source,proto3,enum=openmanet.gnss.v1.GNSSSource" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GNSSSettings) Reset() {
	*x = GNSSSettings{}
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GNSSSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GNSSSettings) ProtoMessage() {}

func (x *GNSSSettings) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GNSSSettings.ProtoReflect.Descriptor instead.
func (*GNSSSettings) Descriptor() ([]byte, []int) {
	return file_openmanet_gnss_v1_gnss_proto_rawDescGZIP(), []int{3}
}

func (x *GNSSSettings) GetEnableGps() bool {
	if x != nil {
		return x.EnableGps
	}
	return false
}

func (x *GNSSSettings) GetSource() GNSSSource {
	if x != nil {
		return x.Source
	}
	return GNSSSource_GNSS_SOURCE_UNSPECIFIED
}

// OutputProtocols configures how position data is distributed to external
// systems such as ATAK / Cursor-on-Target (CoT) consumers and NMEA-capable
// devices on the local network.
type OutputProtocols struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// send_as_nmea enables broadcasting raw NMEA sentences to active devices
	// on the network. Each connected device receives NMEA GGA sentences via
	// UDP on the TAK GPS port.
	SendAsNmea bool `protobuf:"varint,1,opt,name=send_as_nmea,json=sendAsNmea,proto3" json:"send_as_nmea,omitempty"`
	// send_as_cot enables sending position updates as Cursor-on-Target (CoT)
	// messages to ATAK-compatible end-user devices and the SA multicast group.
	SendAsCot bool `protobuf:"varint,2,opt,name=send_as_cot,json=sendAsCot,proto3" json:"send_as_cot,omitempty"`
	// cot_uid is the unique identifier used in outgoing CoT messages. If
	// empty, the system hostname is used as the UID.
	CotUid        string `protobuf:"bytes,3,opt,name=cot_uid,json=cotUid,proto3" json:"cot_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputProtocols) Reset() {
	*x = OutputProtocols{}
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputProtocols) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputProtocols) ProtoMessage() {}

func (x *OutputProtocols) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputProtocols.ProtoReflect.Descriptor instead.
func (*OutputProtocols) Descriptor() ([]byte, []int) {
	return file_openmanet_gnss_v1_gnss_proto_rawDescGZIP(), []int{4}
}

func (x *OutputProtocols) GetSendAsNmea() bool {
	if x != nil {
		return x.SendAsNmea
	}
	return false
}

func (x *OutputProtocols) GetSendAsCot() bool {
	if x != nil {
		return x.SendAsCot
	}
	return false
}

func (x *OutputProtocols) GetCotUid() string {
	if x != nil {
		return x.CotUid
	}
	return ""
}

// GetGNSSStatusResponse contains the current GNSS receiver position and a
// snapshot of the visible satellite constellation. Returned by GetGNSSStatus.
type GetGNSSStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// position holds the latest position fix and accuracy data from the
	// GNSS receiver. May be empty if the receiver has not yet acquired a fix.
	Position *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	// satellite_status holds the current satellite constellation overview,
	// including per-satellite detail and usage counts.
	SatelliteStatus *SatelliteStatus `protobuf:"bytes,2,opt,name=satellite_status,json=satelliteStatus,proto3" json:"satellite_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetGNSSStatusResponse) Reset() {
	*x = GetGNSSStatusResponse{}
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGNSSStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGNSSStatusResponse) ProtoMessage() {}

func (x *GetGNSSStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGNSSStatusResponse.ProtoReflect.Descriptor instead.
func (*GetGNSSStatusResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_gnss_v1_gnss_proto_rawDescGZIP(), []int{5}
}

func (x *GetGNSSStatusResponse) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *GetGNSSStatusResponse) GetSatelliteStatus() *SatelliteStatus {
	if x != nil {
		return x.SatelliteStatus
	}
	return nil
}

// GetGNSSConfigResponse contains the current GNSS settings and output
// protocol configuration. Returned by GetGNSSConfig.
type GetGNSSConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// settings contains the GNSS receiver enable/disable state.
	Settings *GNSSSettings `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	// output_protocols contains the NMEA and CoT distribution configuration.
	OutputProtocols *OutputProtocols `protobuf:"bytes,2,opt,name=output_protocols,json=outputProtocols,proto3" json:"output_protocols,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetGNSSConfigResponse) Reset() {
	*x = GetGNSSConfigResponse{}
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGNSSConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGNSSConfigResponse) ProtoMessage() {}

func (x *GetGNSSConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGNSSConfigResponse.ProtoReflect.Descriptor instead.
func (*GetGNSSConfigResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_gnss_v1_gnss_proto_rawDescGZIP(), []int{6}
}

func (x *GetGNSSConfigResponse) GetSettings() *GNSSSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetGNSSConfigResponse) GetOutputProtocols() *OutputProtocols {
	if x != nil {
		return x.OutputProtocols
	}
	return nil
}

// UpdateGNSSConfigRequest carries the desired GNSS settings and output
// protocol configuration to be persisted.
type UpdateGNSSConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// settings contains the desired GNSS receiver enable/disable state.
	Settings *GNSSSettings `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	// output_protocols contains the desired NMEA and CoT distribution
	// configuration.
	OutputProtocols *OutputProtocols `protobuf:"bytes,2,opt,name=output_protocols,json=outputProtocols,proto3" json:"output_protocols,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateGNSSConfigRequest) Reset() {
	*x = UpdateGNSSConfigRequest{}
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGNSSConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGNSSConfigRequest) ProtoMessage() {}

func (x *UpdateGNSSConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGNSSConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateGNSSConfigRequest) Descriptor() ([]byte, []int) {
	return file_openmanet_gnss_v1_gnss_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateGNSSConfigRequest) GetSettings() *GNSSSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *UpdateGNSSConfigRequest) GetOutputProtocols() *OutputProtocols {
	if x != nil {
		return x.OutputProtocols
	}
	return nil
}

// UpdateGNSSConfigResponse indicates whether the configuration update was
// successfully persisted.
type UpdateGNSSConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success is true when the configuration was persisted without error.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message provides a human-readable description of the outcome, including
	// any warnings or errors encountered during persistence.
	Message       *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGNSSConfigResponse) Reset() {
	*x = UpdateGNSSConfigResponse{}
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGNSSConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGNSSConfigResponse) ProtoMessage() {}

func (x *UpdateGNSSConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_gnss_v1_gnss_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGNSSConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateGNSSConfigResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_gnss_v1_gnss_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateGNSSConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateGNSSConfigResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_openmanet_gnss_v1_gnss_proto protoreflect.FileDescriptor

const file_openmanet_gnss_v1_gnss_proto_rawDesc = "" +
	"\n" +
	"\x1copenmanet/gnss/v1/gnss.proto\x12\x11openmanet.gnss.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x02\n" +
	"\bPosition\x125\n" +
	"\bfix_type\x18\x01 \x01(\x0e2\x1a.openmanet.gnss.v1.FixTypeR\afixType\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x04 \x01(\x01R\baltitude\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\x06 \x01(\x01R\aheading\x12\x12\n" +
	"\x04pdop\x18\a \x01(\x01R\x04pdop\x12\x12\n" +
	"\x04hdop\x18\b \x01(\x01R\x04hdop\x12;\n" +
	"\vlast_update\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUpdate\"\xc3\x01\n" +
	"\tSatellite\x12\x10\n" +
	"\x03prn\x18\x01 \x01(\x05R\x03prn\x12\x1c\n" +
	"\televation\x18\x02 \x01(\x01R\televation\x12\x18\n" +
	"\aazimuth\x18\x03 \x01(\x01R\aazimuth\x12\x10\n" +
	"\x03snr\x18\x04 \x01(\x01R\x03snr\x12\x12\n" +
	"\x04used\x18\x05 \x01(\bR\x04used\x12F\n" +
	"\rconstellation\x18\x06 \x01(\x0e2 .openmanet.gnss.v1.ConstellationR\rconstellation\"\xe3\x01\n" +
	"\x0fSatelliteStatus\x12'\n" +
	"\x0fsatellites_used\x18\x01 \x01(\x05R\x0esatellitesUsed\x12,\n" +
	"\x12satellites_in_view\x18\x02 \x01(\x05R\x10satellitesInView\x12<\n" +
	"\n" +
	"satellites\x18\x03 \x03(\v2\x1c.openmanet.gnss.v1.SatelliteR\n" +
	"satellites\x12;\n" +
	"\vlast_update\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUpdate\"d\n" +
	"\fGNSSSettings\x12\x1d\n" +
	"\n" +
	"enable_gps\x18\x01 \x01(\bR\tenableGps\x125\n" +
	"\x06source\x18\x02 \x01(\x0e2\x1d.openmanet.gnss.v1.GNSSSourceR\x06source\"l\n" +
	"\x0fOutputProtocols\x12 \n" +
	"\fsend_as_nmea\x18\x01 \x01(\bR\n" +
	"sendAsNmea\x12\x1e\n" +
	"\vsend_as_cot\x18\x02 \x01(\bR\tsendAsCot\x12\x17\n" +
	"\acot_uid\x18\x03 \x01(\tR\x06cotUid\"\x9f\x01\n" +
	"\x15GetGNSSStatusResponse\x127\n" +
	"\bposition\x18\x01 \x01(\v2\x1b.openmanet.gnss.v1.PositionR\bposition\x12M\n" +
	"\x10satellite_status\x18\x02 \x01(\v2\".openmanet.gnss.v1.SatelliteStatusR\x0fsatelliteStatus\"\xa3\x01\n" +
	"\x15GetGNSSConfigResponse\x12;\n" +
	"\bsettings\x18\x01 \x01(\v2\x1f.openmanet.gnss.v1.GNSSSettingsR\bsettings\x12M\n" +
	"\x10output_protocols\x18\x02 \x01(\v2\".openmanet.gnss.v1.OutputProtocolsR\x0foutputProtocols\"\xa5\x01\n" +
	"\x17UpdateGNSSConfigRequest\x12;\n" +
	"\bsettings\x18\x01 \x01(\v2\x1f.openmanet.gnss.v1.GNSSSettingsR\bsettings\x12M\n" +
	"\x10output_protocols\x18\x02 \x01(\v2\".openmanet.gnss.v1.OutputProtocolsR\x0foutputProtocols\"_\n" +
	"\x18UpdateGNSSConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message*Z\n" +
	"\aFixType\x12\x18\n" +
	"\x14FIX_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fFIX_TYPE_NO_FIX\x10\x01\x12\x0f\n" +
	"\vFIX_TYPE_2D\x10\x02\x12\x0f\n" +
	"\vFIX_TYPE_3D\x10\x03*\xf6\x01\n" +
	"\rConstellation\x12\x1d\n" +
	"\x19CONSTELLATION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CONSTELLATION_GPS\x10\x01\x12\x16\n" +
	"\x12CONSTELLATION_SBAS\x10\x02\x12\x19\n" +
	"\x15CONSTELLATION_GALILEO\x10\x03\x12\x18\n" +
	"\x14CONSTELLATION_BEIDOU\x10\x04\x12\x16\n" +
	"\x12CONSTELLATION_IMES\x10\x05\x12\x16\n" +
	"\x12CONSTELLATION_QZSS\x10\x06\x12\x19\n" +
	"\x15CONSTELLATION_GLONASS\x10\a\x12\x17\n" +
	"\x13CONSTELLATION_IRNSS\x10\b*a\n" +
	"\n" +
	"GNSSSource\x12\x1b\n" +
	"\x17GNSS_SOURCE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14GNSS_SOURCE_INTERNAL\x10\x01\x12\x1c\n" +
	"\x18GNSS_SOURCE_EXTERNAL_COT\x10\x02B\xcf\x01\n" +
	"\x15com.openmanet.gnss.v1B\tGnssProtoP\x01ZEgithub.com/openmanet/openmanetd/internal/api/openmanet/gnss/v1;gnssv1\xa2\x02\x03OGX\xaa\x02\x11Openmanet.Gnss.V1\xca\x02\x11Openmanet\\Gnss\\V1\xe2\x02\x1dOpenmanet\\Gnss\\V1\\GPBMetadata\xea\x02\x13Openmanet::Gnss::V1b\x06proto3"

var (
	file_openmanet_gnss_v1_gnss_proto_rawDescOnce sync.Once
	file_openmanet_gnss_v1_gnss_proto_rawDescData []byte
)

func file_openmanet_gnss_v1_gnss_proto_rawDescGZIP() []byte {
	file_openmanet_gnss_v1_gnss_proto_rawDescOnce.Do(func() {
		file_openmanet_gnss_v1_gnss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openmanet_gnss_v1_gnss_proto_rawDesc), len(file_openmanet_gnss_v1_gnss_proto_rawDesc)))
	})
	return file_openmanet_gnss_v1_gnss_proto_rawDescData
}

var file_openmanet_gnss_v1_gnss_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_openmanet_gnss_v1_gnss_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_openmanet_gnss_v1_gnss_proto_goTypes = []any{
	(FixType)(0),                     // 0: openmanet.gnss.v1.FixType
	(Constellation)(0),               // 1: openmanet.gnss.v1.Constellation
	(GNSSSource)(0),                  // 2: openmanet.gnss.v1.GNSSSource
	(*Position)(nil),                 // 3: openmanet.gnss.v1.Position
	(*Satellite)(nil),                // 4: openmanet.gnss.v1.Satellite
	(*SatelliteStatus)(nil),          // 5: openmanet.gnss.v1.SatelliteStatus
	(*GNSSSettings)(nil),             // 6: openmanet.gnss.v1.GNSSSettings
	(*OutputProtocols)(nil),          // 7: openmanet.gnss.v1.OutputProtocols
	(*GetGNSSStatusResponse)(nil),    // 8: openmanet.gnss.v1.GetGNSSStatusResponse
	(*GetGNSSConfigResponse)(nil),    // 9: openmanet.gnss.v1.GetGNSSConfigResponse
	(*UpdateGNSSConfigRequest)(nil),  // 10: openmanet.gnss.v1.UpdateGNSSConfigRequest
	(*UpdateGNSSConfigResponse)(nil), // 11: openmanet.gnss.v1.UpdateGNSSConfigResponse
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
}
var file_openmanet_gnss_v1_gnss_proto_depIdxs = []int32{
	0,  // 0: openmanet.gnss.v1.Position.fix_type:type_name -> openmanet.gnss.v1.FixType
	12, // 1: openmanet.gnss.v1.Position.last_update:type_name -> google.protobuf.Timestamp
	1,  // 2: openmanet.gnss.v1.Satellite.constellation:type_name -> openmanet.gnss.v1.Constellation
	4,  // 3: openmanet.gnss.v1.SatelliteStatus.satellites:type_name -> openmanet.gnss.v1.Satellite
	12, // 4: openmanet.gnss.v1.SatelliteStatus.last_update:type_name -> google.protobuf.Timestamp
	2,  // 5: openmanet.gnss.v1.GNSSSettings.source:type_name -> openmanet.gnss.v1.GNSSSource
	3,  // 6: openmanet.gnss.v1.GetGNSSStatusResponse.position:type_name -> openmanet.gnss.v1.Position
	5,  // 7: openmanet.gnss.v1.GetGNSSStatusResponse.satellite_status:type_name -> openmanet.gnss.v1.SatelliteStatus
	6,  // 8: openmanet.gnss.v1.GetGNSSConfigResponse.settings:type_name -> openmanet.gnss.v1.GNSSSettings
	7,  // 9: openmanet.gnss.v1.GetGNSSConfigResponse.output_protocols:type_name -> openmanet.gnss.v1.OutputProtocols
	6,  // 10: openmanet.gnss.v1.UpdateGNSSConfigRequest.settings:type_name -> openmanet.gnss.v1.GNSSSettings
	7,  // 11: openmanet.gnss.v1.UpdateGNSSConfigRequest.output_protocols:type_name -> openmanet.gnss.v1.OutputProtocols
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_openmanet_gnss_v1_gnss_proto_init() }
func file_openmanet_gnss_v1_gnss_proto_init() {
	if File_openmanet_gnss_v1_gnss_proto != nil {
		return
	}
	file_openmanet_gnss_v1_gnss_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmanet_gnss_v1_gnss_proto_rawDesc), len(file_openmanet_gnss_v1_gnss_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openmanet_gnss_v1_gnss_proto_goTypes,
		DependencyIndexes: file_openmanet_gnss_v1_gnss_proto_depIdxs,
		EnumInfos:         file_openmanet_gnss_v1_gnss_proto_enumTypes,
		MessageInfos:      file_openmanet_gnss_v1_gnss_proto_msgTypes,
	}.Build()
	File_openmanet_gnss_v1_gnss_proto = out.File
	file_openmanet_gnss_v1_gnss_proto_goTypes = nil
	file_openmanet_gnss_v1_gnss_proto_depIdxs = nil
}
