// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openmanet/mesh_topology/v1/mesh_topology.proto

package mesh_topologyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MeshNode is one physical node in the mesh, as reported by alfred /
// batadv-vis -f jsondoc and enriched with /tmp/bat-hosts metadata plus
// self-originator overlay data.
type MeshNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mac is the node's primary MAC (its bat0 address from the vis payload).
	Mac string `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	// secondary_macs are the other MACs this node publishes (one per extra
	// hard interface). Kept so edges keyed on a secondary MAC can be
	// resolved back to a single MeshNode.
	SecondaryMacs []string `protobuf:"bytes,2,rep,name=secondary_macs,json=secondaryMacs,proto3" json:"secondary_macs,omitempty"`
	// hostname is the node's base hostname from /tmp/bat-hosts, with the
	// "_<iface>" suffix stripped. Empty when bat-hosts has no entry.
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// segment is the rendering segment this node belongs to from the
	// serving node's point of view: "local" when the serving node reaches
	// it over a non-vxlan0 interface, "remote" when the best route is
	// over vxlan0 (BLOS). Always "local" for the serving node itself.
	Segment string `protobuf:"bytes,4,opt,name=segment,proto3" json:"segment,omitempty"`
	// client_count is the number of non-mesh MACs attached to this node
	// (the length of the vis "clients" array — transtable entries such
	// as laptops or phones bridged via ethernet or AP).
	ClientCount int32 `protobuf:"varint,5,opt,name=client_count,json=clientCount,proto3" json:"client_count,omitempty"`
	// hops_from_self is the number of forwarding hops from the serving
	// node to this node, as derived from the serving node's originator
	// table. 0 for the serving node itself; 99 for "unknown".
	HopsFromSelf int32 `protobuf:"varint,6,opt,name=hops_from_self,json=hopsFromSelf,proto3" json:"hops_from_self,omitempty"`
	// my_hard_ifname is the local interface the serving node uses to
	// reach this node (e.g. "wlan0", "vxlan0"). Empty when the serving
	// node has no route to this node in its originator table.
	MyHardIfname string `protobuf:"bytes,7,opt,name=my_hard_ifname,json=myHardIfname,proto3" json:"my_hard_ifname,omitempty"`
	// is_self is true when this node is the serving node.
	IsSelf bool `protobuf:"varint,8,opt,name=is_self,json=isSelf,proto3" json:"is_self,omitempty"`
	// remote_gateway_mac is the MAC of the direct BLOS neighbor (vxlan0)
	// through which the serving node reaches this remote node. Empty for
	// local-segment nodes. Remote nodes sharing the same gateway form one
	// remote mesh segment in the UI; distinct gateways produce distinct
	// segments.
	RemoteGatewayMac string `protobuf:"bytes,9,opt,name=remote_gateway_mac,json=remoteGatewayMac,proto3" json:"remote_gateway_mac,omitempty"`
	// gossip_stale is true when the mesh-neighbors gossip record for this
	// node has not been refreshed within the snapshotter's StaleAge
	// window, or when no gossip record exists at all. The UI dims stale
	// hosts to signal that their topology data is aging.
	GossipStale bool `protobuf:"varint,10,opt,name=gossip_stale,json=gossipStale,proto3" json:"gossip_stale,omitempty"`
	// gossip_age_seconds is the age (in whole seconds) of the publisher's
	// most recent gossip record for this node — the delta between the
	// serving node's "now" and the payload's collected_at. -1 when no
	// record exists or the publisher did not timestamp the payload. Unset
	// (0) for self, which is always current.
	GossipAgeSeconds int32 `protobuf:"varint,11,opt,name=gossip_age_seconds,json=gossipAgeSeconds,proto3" json:"gossip_age_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MeshNode) Reset() {
	*x = MeshNode{}
	mi := &file_openmanet_mesh_topology_v1_mesh_topology_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshNode) ProtoMessage() {}

func (x *MeshNode) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_mesh_topology_v1_mesh_topology_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshNode.ProtoReflect.Descriptor instead.
func (*MeshNode) Descriptor() ([]byte, []int) {
	return file_openmanet_mesh_topology_v1_mesh_topology_proto_rawDescGZIP(), []int{0}
}

func (x *MeshNode) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *MeshNode) GetSecondaryMacs() []string {
	if x != nil {
		return x.SecondaryMacs
	}
	return nil
}

func (x *MeshNode) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MeshNode) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *MeshNode) GetClientCount() int32 {
	if x != nil {
		return x.ClientCount
	}
	return 0
}

func (x *MeshNode) GetHopsFromSelf() int32 {
	if x != nil {
		return x.HopsFromSelf
	}
	return 0
}

func (x *MeshNode) GetMyHardIfname() string {
	if x != nil {
		return x.MyHardIfname
	}
	return ""
}

func (x *MeshNode) GetIsSelf() bool {
	if x != nil {
		return x.IsSelf
	}
	return false
}

func (x *MeshNode) GetRemoteGatewayMac() string {
	if x != nil {
		return x.RemoteGatewayMac
	}
	return ""
}

func (x *MeshNode) GetGossipStale() bool {
	if x != nil {
		return x.GossipStale
	}
	return false
}

func (x *MeshNode) GetGossipAgeSeconds() int32 {
	if x != nil {
		return x.GossipAgeSeconds
	}
	return 0
}

// MeshEdge is one link in the mesh, canonicalized so A↔B appears once
// regardless of whether vis reported it from A's or B's perspective.
type MeshEdge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// from_mac is the lexically-smaller endpoint MAC (lowercased).
	FromMac string `protobuf:"bytes,1,opt,name=from_mac,json=fromMac,proto3" json:"from_mac,omitempty"`
	// to_mac is the lexically-larger endpoint MAC (lowercased).
	ToMac string `protobuf:"bytes,2,opt,name=to_mac,json=toMac,proto3" json:"to_mac,omitempty"`
	// metric is the raw link metric reported by vis. For BATMAN_IV this
	// is 255/TQ (lower is better). For BATMAN_V it is throughput-derived
	// (see the algorithm field on the enclosing MeshTopology). Zero when
	// vis emitted no parseable metric.
	Metric float64 `protobuf:"fixed64,3,opt,name=metric,proto3" json:"metric,omitempty"`
	// blos is true when the two endpoints sit in different segments —
	// i.e. the edge bridges a BLOS (vxlan0) tunnel.
	Blos bool `protobuf:"varint,4,opt,name=blos,proto3" json:"blos,omitempty"`
	// on_my_path is true when this edge appears as (orig, best_next_hop)
	// in the serving node's originator table — i.e. the serving node
	// forwards traffic over this link.
	OnMyPath      bool `protobuf:"varint,5,opt,name=on_my_path,json=onMyPath,proto3" json:"on_my_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshEdge) Reset() {
	*x = MeshEdge{}
	mi := &file_openmanet_mesh_topology_v1_mesh_topology_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshEdge) ProtoMessage() {}

func (x *MeshEdge) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_mesh_topology_v1_mesh_topology_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshEdge.ProtoReflect.Descriptor instead.
func (*MeshEdge) Descriptor() ([]byte, []int) {
	return file_openmanet_mesh_topology_v1_mesh_topology_proto_rawDescGZIP(), []int{1}
}

func (x *MeshEdge) GetFromMac() string {
	if x != nil {
		return x.FromMac
	}
	return ""
}

func (x *MeshEdge) GetToMac() string {
	if x != nil {
		return x.ToMac
	}
	return ""
}

func (x *MeshEdge) GetMetric() float64 {
	if x != nil {
		return x.Metric
	}
	return 0
}

func (x *MeshEdge) GetBlos() bool {
	if x != nil {
		return x.Blos
	}
	return false
}

func (x *MeshEdge) GetOnMyPath() bool {
	if x != nil {
		return x.OnMyPath
	}
	return false
}

// MeshTopology is the full mesh graph: every reachable node's neighbor
// set as published to alfred by every node's batadv-vis -s, enriched
// with bat-hosts hostnames and the serving node's own routing overlay.
type MeshTopology struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// self_mac is the MAC of the serving node's bat0 interface. Empty
	// when the interface is not yet present (batman-adv module loading).
	SelfMac string `protobuf:"bytes,1,opt,name=self_mac,json=selfMac,proto3" json:"self_mac,omitempty"`
	// self_hostname is the base hostname of the serving node — its
	// bat-hosts entry with the "_bat0" suffix stripped. Empty when
	// bat-hosts has no entry for self_mac.
	SelfHostname string `protobuf:"bytes,2,opt,name=self_hostname,json=selfHostname,proto3" json:"self_hostname,omitempty"`
	// algorithm is the batman-adv routing algorithm as reported by
	// batadv-vis: "BATMAN_IV" for code 4, "BATMAN_V" for code 15, empty
	// otherwise. Determines how the per-edge metric field should be
	// formatted in the UI.
	Algorithm string `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// nodes is the set of physical mesh nodes — one entry per primary
	// MAC. Sorted (is_self desc, hostname asc) for stable rendering.
	Nodes []*MeshNode `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// edges is the canonical set of mesh links. Sorted (blos asc,
	// from_mac asc, to_mac asc) for stable rendering.
	Edges []*MeshEdge `protobuf:"bytes,5,rep,name=edges,proto3" json:"edges,omitempty"`
	// collected_at is the wall-clock time the snapshot was produced on
	// the serving node.
	CollectedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	// gossip_coverage reports how many mesh members are currently
	// publishing MeshNeighbors gossip. Lets the UI show a "GOSSIP N/M"
	// badge so operators can spot partial coverage.
	GossipCoverage *GossipCoverage `protobuf:"bytes,7,opt,name=gossip_coverage,json=gossipCoverage,proto3" json:"gossip_coverage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MeshTopology) Reset() {
	*x = MeshTopology{}
	mi := &file_openmanet_mesh_topology_v1_mesh_topology_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshTopology) ProtoMessage() {}

func (x *MeshTopology) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_mesh_topology_v1_mesh_topology_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshTopology.ProtoReflect.Descriptor instead.
func (*MeshTopology) Descriptor() ([]byte, []int) {
	return file_openmanet_mesh_topology_v1_mesh_topology_proto_rawDescGZIP(), []int{2}
}

func (x *MeshTopology) GetSelfMac() string {
	if x != nil {
		return x.SelfMac
	}
	return ""
}

func (x *MeshTopology) GetSelfHostname() string {
	if x != nil {
		return x.SelfHostname
	}
	return ""
}

func (x *MeshTopology) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *MeshTopology) GetNodes() []*MeshNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *MeshTopology) GetEdges() []*MeshEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *MeshTopology) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *MeshTopology) GetGossipCoverage() *GossipCoverage {
	if x != nil {
		return x.GossipCoverage
	}
	return nil
}

// GossipCoverage summarizes MeshNeighbors gossip participation across
// the mesh at the serving node's most recent refresh.
type GossipCoverage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// published is the number of primary MACs for which a gossip record
	// was present and not stale.
	Published int32 `protobuf:"varint,1,opt,name=published,proto3" json:"published,omitempty"`
	// total is the number of primary MACs the serving node is aware of
	// (from vis + originators). When published == total every mesh
	// member is participating.
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipCoverage) Reset() {
	*x = GossipCoverage{}
	mi := &file_openmanet_mesh_topology_v1_mesh_topology_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipCoverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipCoverage) ProtoMessage() {}

func (x *GossipCoverage) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_mesh_topology_v1_mesh_topology_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipCoverage.ProtoReflect.Descriptor instead.
func (*GossipCoverage) Descriptor() ([]byte, []int) {
	return file_openmanet_mesh_topology_v1_mesh_topology_proto_rawDescGZIP(), []int{3}
}

func (x *GossipCoverage) GetPublished() int32 {
	if x != nil {
		return x.Published
	}
	return 0
}

func (x *GossipCoverage) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_openmanet_mesh_topology_v1_mesh_topology_proto protoreflect.FileDescriptor

const file_openmanet_mesh_topology_v1_mesh_topology_proto_rawDesc = "" +
	"\n" +
	".openmanet/mesh_topology/v1/mesh_topology.proto\x12\x1aopenmanet.mesh_topology.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x03\n" +
	"\bMeshNode\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\tR\x03mac\x12%\n" +
	"\x0esecondary_macs\x18\x02 \x03(\tR\rsecondaryMacs\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x18\n" +
	"\asegment\x18\x04 \x01(\tR\asegment\x12!\n" +
	"\fclient_count\x18\x05 \x01(\x05R\vclientCount\x12$\n" +
	"\x0ehops_from_self\x18\x06 \x01(\x05R\fhopsFromSelf\x12$\n" +
	"\x0emy_hard_ifname\x18\a \x01(\tR\fmyHardIfname\x12\x17\n" +
	"\ais_self\x18\b \x01(\bR\x06isSelf\x12,\n" +
	"\x12remote_gateway_mac\x18\t \x01(\tR\x10remoteGatewayMac\x12!\n" +
	"\fgossip_stale\x18\n" +
	" \x01(\bR\vgossipStale\x12,\n" +
	"\x12gossip_age_seconds\x18\v \x01(\x05R\x10gossipAgeSeconds\"\x86\x01\n" +
	"\bMeshEdge\x12\x19\n" +
	"\bfrom_mac\x18\x01 \x01(\tR\afromMac\x12\x15\n" +
	"\x06to_mac\x18\x02 \x01(\tR\x05toMac\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\x01R\x06metric\x12\x12\n" +
	"\x04blos\x18\x04 \x01(\bR\x04blos\x12\x1c\n" +
	"\n" +
	"on_my_path\x18\x05 \x01(\bR\bonMyPath\"\xf8\x02\n" +
	"\fMeshTopology\x12\x19\n" +
	"\bself_mac\x18\x01 \x01(\tR\aselfMac\x12#\n" +
	"\rself_hostname\x18\x02 \x01(\tR\fselfHostname\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x12:\n" +
	"\x05nodes\x18\x04 \x03(\v2$.openmanet.mesh_topology.v1.MeshNodeR\x05nodes\x12:\n" +
	"\x05edges\x18\x05 \x03(\v2$.openmanet.mesh_topology.v1.MeshEdgeR\x05edges\x12=\n" +
	"\fcollected_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x12S\n" +
	"\x0fgossip_coverage\x18\a \x01(\v2*.openmanet.mesh_topology.v1.GossipCoverageR\x0egossipCoverage\"D\n" +
	"\x0eGossipCoverage\x12\x1c\n" +
	"\tpublished\x18\x01 \x01(\x05R\tpublished\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05totalB\x92\x02\n" +
	"\x1ecom.openmanet.mesh_topology.v1B\x11MeshTopologyProtoP\x01ZWgithub.com/openmanet/openmanetd/internal/api/openmanet/mesh_topology/v1;mesh_topologyv1\xa2\x02\x03OMX\xaa\x02\x19Openmanet.MeshTopology.V1\xca\x02\x19Openmanet\\MeshTopology\\V1\xe2\x02%Openmanet\\MeshTopology\\V1\\GPBMetadata\xea\x02\x1bOpenmanet::MeshTopology::V1b\x06proto3"

var (
	file_openmanet_mesh_topology_v1_mesh_topology_proto_rawDescOnce sync.Once
	file_openmanet_mesh_topology_v1_mesh_topology_proto_rawDescData []byte
)

func file_openmanet_mesh_topology_v1_mesh_topology_proto_rawDescGZIP() []byte {
	file_openmanet_mesh_topology_v1_mesh_topology_proto_rawDescOnce.Do(func() {
		file_openmanet_mesh_topology_v1_mesh_topology_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openmanet_mesh_topology_v1_mesh_topology_proto_rawDesc), len(file_openmanet_mesh_topology_v1_mesh_topology_proto_rawDesc)))
	})
	return file_openmanet_mesh_topology_v1_mesh_topology_proto_rawDescData
}

var file_openmanet_mesh_topology_v1_mesh_topology_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_openmanet_mesh_topology_v1_mesh_topology_proto_goTypes = []any{
	(*MeshNode)(nil),              // 0: openmanet.mesh_topology.v1.MeshNode
	(*MeshEdge)(nil),              // 1: openmanet.mesh_topology.v1.MeshEdge
	(*MeshTopology)(nil),          // 2: openmanet.mesh_topology.v1.MeshTopology
	(*GossipCoverage)(nil),        // 3: openmanet.mesh_topology.v1.GossipCoverage
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_openmanet_mesh_topology_v1_mesh_topology_proto_depIdxs = []int32{
	0, // 0: openmanet.mesh_topology.v1.MeshTopology.nodes:type_name -> openmanet.mesh_topology.v1.MeshNode
	1, // 1: openmanet.mesh_topology.v1.MeshTopology.edges:type_name -> openmanet.mesh_topology.v1.MeshEdge
	4, // 2: openmanet.mesh_topology.v1.MeshTopology.collected_at:type_name -> google.protobuf.Timestamp
	3, // 3: openmanet.mesh_topology.v1.MeshTopology.gossip_coverage:type_name -> openmanet.mesh_topology.v1.GossipCoverage
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_openmanet_mesh_topology_v1_mesh_topology_proto_init() }
func file_openmanet_mesh_topology_v1_mesh_topology_proto_init() {
	if File_openmanet_mesh_topology_v1_mesh_topology_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmanet_mesh_topology_v1_mesh_topology_proto_rawDesc), len(file_openmanet_mesh_topology_v1_mesh_topology_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openmanet_mesh_topology_v1_mesh_topology_proto_goTypes,
		DependencyIndexes: file_openmanet_mesh_topology_v1_mesh_topology_proto_depIdxs,
		MessageInfos:      file_openmanet_mesh_topology_v1_mesh_topology_proto_msgTypes,
	}.Build()
	File_openmanet_mesh_topology_v1_mesh_topology_proto = out.File
	file_openmanet_mesh_topology_v1_mesh_topology_proto_goTypes = nil
	file_openmanet_mesh_topology_v1_mesh_topology_proto_depIdxs = nil
}
