// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openmanet/mesh_topology/v1/mesh_topology_service.proto

package mesh_topologyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMeshTopologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topology      *MeshTopology          `protobuf:"bytes,1,opt,name=topology,proto3" json:"topology,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeshTopologyResponse) Reset() {
	*x = GetMeshTopologyResponse{}
	mi := &file_openmanet_mesh_topology_v1_mesh_topology_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeshTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeshTopologyResponse) ProtoMessage() {}

func (x *GetMeshTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_mesh_topology_v1_mesh_topology_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeshTopologyResponse.ProtoReflect.Descriptor instead.
func (*GetMeshTopologyResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_mesh_topology_v1_mesh_topology_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetMeshTopologyResponse) GetTopology() *MeshTopology {
	if x != nil {
		return x.Topology
	}
	return nil
}

var File_openmanet_mesh_topology_v1_mesh_topology_service_proto protoreflect.FileDescriptor

const file_openmanet_mesh_topology_v1_mesh_topology_service_proto_rawDesc = "" +
	"\n" +
	"6openmanet/mesh_topology/v1/mesh_topology_service.proto\x12\x1aopenmanet.mesh_topology.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a.openmanet/mesh_topology/v1/mesh_topology.proto\"_\n" +
	"\x17GetMeshTopologyResponse\x12D\n" +
	"\btopology\x18\x01 \x01(\v2(.openmanet.mesh_topology.v1.MeshTopologyR\btopology2u\n" +
	"\x13MeshTopologyService\x12^\n" +
	"\x0fGetMeshTopology\x12\x16.google.protobuf.Empty\x1a3.openmanet.mesh_topology.v1.GetMeshTopologyResponseB\x99\x02\n" +
	"\x1ecom.openmanet.mesh_topology.v1B\x18MeshTopologyServiceProtoP\x01ZWgithub.com/openmanet/openmanetd/internal/api/openmanet/mesh_topology/v1;mesh_topologyv1\xa2\x02\x03OMX\xaa\x02\x19Openmanet.MeshTopology.V1\xca\x02\x19Openmanet\\MeshTopology\\V1\xe2\x02%Openmanet\\MeshTopology\\V1\\GPBMetadata\xea\x02\x1bOpenmanet::MeshTopology::V1b\x06proto3"

var (
	file_openmanet_mesh_topology_v1_mesh_topology_service_proto_rawDescOnce sync.Once
	file_openmanet_mesh_topology_v1_mesh_topology_service_proto_rawDescData []byte
)

func file_openmanet_mesh_topology_v1_mesh_topology_service_proto_rawDescGZIP() []byte {
	file_openmanet_mesh_topology_v1_mesh_topology_service_proto_rawDescOnce.Do(func() {
		file_openmanet_mesh_topology_v1_mesh_topology_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openmanet_mesh_topology_v1_mesh_topology_service_proto_rawDesc), len(file_openmanet_mesh_topology_v1_mesh_topology_service_proto_rawDesc)))
	})
	return file_openmanet_mesh_topology_v1_mesh_topology_service_proto_rawDescData
}

var file_openmanet_mesh_topology_v1_mesh_topology_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_openmanet_mesh_topology_v1_mesh_topology_service_proto_goTypes = []any{
	(*GetMeshTopologyResponse)(nil), // 0: openmanet.mesh_topology.v1.GetMeshTopologyResponse
	(*MeshTopology)(nil),            // 1: openmanet.mesh_topology.v1.MeshTopology
	(*emptypb.Empty)(nil),           // 2: google.protobuf.Empty
}
var file_openmanet_mesh_topology_v1_mesh_topology_service_proto_depIdxs = []int32{
	1, // 0: openmanet.mesh_topology.v1.GetMeshTopologyResponse.topology:type_name -> openmanet.mesh_topology.v1.MeshTopology
	2, // 1: openmanet.mesh_topology.v1.MeshTopologyService.GetMeshTopology:input_type -> google.protobuf.Empty
	0, // 2: openmanet.mesh_topology.v1.MeshTopologyService.GetMeshTopology:output_type -> openmanet.mesh_topology.v1.GetMeshTopologyResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_openmanet_mesh_topology_v1_mesh_topology_service_proto_init() }
func file_openmanet_mesh_topology_v1_mesh_topology_service_proto_init() {
	if File_openmanet_mesh_topology_v1_mesh_topology_service_proto != nil {
		return
	}
	file_openmanet_mesh_topology_v1_mesh_topology_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmanet_mesh_topology_v1_mesh_topology_service_proto_rawDesc), len(file_openmanet_mesh_topology_v1_mesh_topology_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openmanet_mesh_topology_v1_mesh_topology_service_proto_goTypes,
		DependencyIndexes: file_openmanet_mesh_topology_v1_mesh_topology_service_proto_depIdxs,
		MessageInfos:      file_openmanet_mesh_topology_v1_mesh_topology_service_proto_msgTypes,
	}.Build()
	File_openmanet_mesh_topology_v1_mesh_topology_service_proto = out.File
	file_openmanet_mesh_topology_v1_mesh_topology_service_proto_goTypes = nil
	file_openmanet_mesh_topology_v1_mesh_topology_service_proto_depIdxs = nil
}
